'use strict';
// The lesson vocabulary is the only source. Never fall back to arcade sample words.
const EpisodeGames=(()=>{
 const ids=Array.from({length:27},(_,i)=>'G'+String(i+2).padStart(2,'0'));
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 // Words is authoritative for proper names; do not capitalize ordinary vocabulary.
 function pack(vocab){const words=[],excluded=[],seen=new Set();for(const w of vocab||[]){const raw=String(w.word||'').trim(),zh=String(w.meaningZh||w.meaning||'').trim();if(!/^[a-z]{2,16}$/i.test(raw)||!zh){excluded.push(raw||'未命名单词');continue}const key=raw.toLowerCase();if(seen.has(key))continue;seen.add(key);const preserveCase=w.preserveCase===true||/proper|专有/i.test(w.partOfSpeech||'')||(/^[A-Z][a-z]+$/.test(raw)&&!['Good','Thank','Internet'].includes(raw))||/^(TV|CD|DVD|BC|AD|AM|PM|USA|UK|US|UN|EU|NASA|BBC|DNA|RNA|USB|AI|IT|ABCs)$/.test(raw);words.push({en:preserveCase?raw:key,zh,preserveCase})}return {words,excluded}}
 function choose(previous=[]){const pool=ids.filter(id=>!previous.includes(id));for(let i=pool.length-1;i>0;i--){let j;do{const n=new Uint32Array(1);crypto.getRandomValues(n);const limit=Math.floor(4294967296/(i+1))*(i+1);if(n[0]<limit){j=n[0]%(i+1);break}}while(true);[pool[i],pool[j]]=[pool[j],pool[i]]}return pool.slice(0,3)}
 function panel(d){const p=pack(d.vocab);if(p.words.length<4)return `<section class="episode-games-empty"><h2>Games · 本集词汇游戏</h2><p>本集暂时没有足够的可用单词（至少需要 4 个）。</p><p>请先学习 Words；我们不会使用其他集或示例词填充游戏。</p>${p.excluded.length?`<p>暂不支持的词条：${p.excluded.map(escape).join('、')}</p>`:''}</section>`;
 return `<section class="episode-games"><div class="episode-games-head"><div><h2>Games · 本集词汇游戏</h2><p>Episode ${escape(d.episodeId)} · ${p.words.length} 个本集单词 · 每次打开随机出现 3 款</p></div><button class="btn secondary games-refresh" type="button">🎲 换一组游戏</button></div>${p.excluded.length?`<details class="games-exclusions"><summary>${p.excluded.length} 个词条暂不适用于游戏</summary><p>${p.excluded.map(escape).join('、')}</p><p>目前游戏支持 2–16 个英文字母的单词；短语、含标点的词及缺少中文释义的词仍保留在 Words 中，不拆词或替换。</p></details>`:''}<p class="games-practice-note">游戏为课后练习，不影响 Quiz 解锁进度。“换一组”会结束当前游戏。</p><iframe class="episode-games-frame" title="Episode ${escape(d.episodeId)} 词汇游戏" src="arcade/index.html?embedded=1" allow="fullscreen" loading="eager"></iframe></section>`}
 function bind(root,d){for(const section of root.querySelectorAll('.episode-games:not([data-bound])')){section.dataset.bound='1';const frame=section.querySelector('iframe'),p=pack(d.vocab);frame.gamePayload={type:'episode-games:init',episodeKey:`${d.seriesId}:${d.episodeId}`,title:`Episode ${d.episodeId} · ${d.ep.title}`,words:p.words,ids:choose()};const send=()=>frame.contentWindow?.postMessage(frame.gamePayload,location.origin);frame.addEventListener('load',send);section.querySelector('.games-refresh').onclick=()=>{frame.gamePayload.ids=choose(frame.gamePayload.ids);send()};send()}}
 window.addEventListener('message',event=>{if(event.origin!==location.origin)return;const frame=[...document.querySelectorAll('.episode-games-frame')].find(f=>f.contentWindow===event.source);if(!frame?.gamePayload)return;if(event.data?.type==='episode-games:ready')frame.contentWindow.postMessage(frame.gamePayload,location.origin);if(event.data?.type==='episode-games:height'&&Number.isFinite(event.data.height))frame.style.height=Math.min(2400,Math.max(440,event.data.height))+'px'});
 return {panel,bind,pack,choose};
})();
