const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const store=new Map(),window={addEventListener(){}};let failPoints=false,queue=Promise.resolve();
const ctx=vm.createContext({window,document:{querySelectorAll:()=>[],getElementById:()=>null},navigator:{locks:{request:(key,fn)=>{const next=queue.then(fn);queue=next.catch(()=>{});return next}}},crypto:require('node:crypto').webcrypto,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>{if(failPoints&&k==='sf_points'){failPoints=false;throw Error('storage full')}store.set(k,String(v))}},setTimeout,clearTimeout});
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
vm.runInContext(read('js/cloud-account.js'),ctx);
vm.runInContext(read('js/episode-games.js')+'\nglobalThis.api=EpisodeGames;',ctx);
vm.runInContext(read('js/app.js').replace(/App\.start\(\);\s*$/,'globalThis.app=App;'),ctx);
const api=ctx.api,app=ctx.app,cloud=window.SFCloud;
const d={seriesId:'test',episodeId:1,vocab:['apple','bridge','cloud','dragon','two words'].map(word=>({word,meaningZh:'词'}))};
(async()=>{
 app.addPoints(4);
 assert.equal(api.status(d).unlocked,false);
 assert.equal(api.status(d,{'test:1':{modules:{words:true}}}).unlocked,false);
 app.recordTypingCorrect('test',2,'apple');assert.equal(api.status(d).done,0);
 app.recordTypingCorrect('test',1,'apple');app.recordTypingCorrect('test',1,'APPLE');app.recordTypingCorrect('test',1,'bridge');
 assert.equal(api.status(d).done,2);assert.equal(api.status(d).required,3);assert.equal(api.status(d).unlocked,false);
 assert.equal((await api.charge(d,'G07','locked')).ok,false);assert.equal(app.getPoints(),4);
 app.recordTypingCorrect('test',1,'cloud');assert.equal(api.status(d).unlocked,true);
 assert.equal(api.status({...d,vocab:d.vocab.slice(0,4)}).required,2);
 const before=cloud.snapshot();
 assert.equal((await api.charge(d,'G07','first')).ok,true);assert.equal(app.getPoints(),2);
 assert.equal((await api.charge(d,'G07','first')).ok,false);assert.equal(app.getPoints(),2);
 const after=cloud.snapshot();assert.equal(cloud.merge(before,after).points,2);assert.equal(cloud.merge(after,before).points,2);assert.equal(cloud.merge(after,after).points,2);
 assert.equal(cloud.merge(before,after).progress['test:1'].typingCorrect.apple,true);
 const concurrent=await Promise.all([api.charge(d,'G03','second'),api.charge(d,'G05','third')]);assert.equal(concurrent.filter(r=>r.ok).length,1);assert.equal(app.getPoints(),0);
 assert.equal((await api.charge(d,'G03','poor')).ok,false);assert.equal(cloud.merge(before,cloud.snapshot()).points,0);
 app.addPoints(2);const spending=cloud.spent(app.storage('progress'));failPoints=true;
 assert.equal((await api.charge(d,'G07','failure')).ok,false);assert.equal(app.getPoints(),2);assert.equal(cloud.spent(app.storage('progress')),spending);
 assert.equal((await api.charge(d,'G07','closed',()=>false)).ok,false);assert.equal(app.getPoints(),2);
 const a={points:2,progress:{'test:1':{modules:{},pointSpends:{a:{amount:2}}}}},b={points:2,progress:{'test:1':{modules:{},pointSpends:{b:{amount:2}}}}};assert.equal(cloud.merge(a,b).points,0);
 cloud.user={id:'another-account'};assert.equal(api.status(d).unlocked,false);assert.equal(app.getPoints(),0);cloud.user=null;
 assert.equal(api.status(d).unlocked,true);assert.equal(app.getPoints(),2);
 assert.ok(!api.panel(d).includes('games-refresh'));assert.ok(!api.panel(d).includes('换一组'));
 console.log('PASS: unique correct words, odd/even 50% threshold, episode/account isolation, exact 2-point debit, duplicate/concurrent/closed/failed requests, insufficient balance, cloud spend union without resurrection.');
})().catch(e=>{console.error(e);process.exitCode=1});
