const games=[['G02','纵横填字','Crossword','🧩','ready'],['G03','中英文翻翻乐','Memory Match','🃏','ready'],['G04','黄金矿工','Gold Miner','⛏️'],['G05','单词消消乐','Match-3','💎'],['G06','单词找找看','Word Search','🔎','ready'],['G07','单词泡泡龙','Puzzle Bobble','🫧'],['G08','单词抓娃娃','Claw Machine','🕹️'],['G09','单词切切乐','Fruit Ninja','⚔️'],['G10','单词钓鱼','Fishing','🎣'],['G11','单词分拣工厂','Sorting','🏭'],['G12','单词气球爆破','Balloon Pop','🎈'],['G13','单词保龄球','Bowling','🎳'],['G14','单词飞镖','Darts','🎯'],['G15','字母磁铁','Letter Magnet','🧲'],['G16','星际字母收集','Space Collector','🚀'],['G17','单词打砖块','Breakout','🧱'],['G18','深海寻字母','Underwater','🐠'],['G19','单词接接乐','Catch Game','🧺','ready'],['G20','主题单词迷阵','Strands','🧵'],['G21','单词吃豆人','Pac-Man','👾'],['G22','空气曲棍球','Air Hockey','🏒'],['G23','太空入侵者','Space Invaders','👽'],['G24','坦克大战','Battle City','🛡️'],['G25','炸弹人','Bomberman','💣'],['G26','淘金者','Lode Runner','🏃'],['G27','1942空战','1942','✈️'],['G28','拆迁队','Wrecking Crew','🔨']];
let words=JSON.parse(localStorage.arcadeWords||'[{"en":"apple","zh":"苹果"},{"en":"bridge","zh":"桥"},{"en":"cloud","zh":"云"},{"en":"dragon","zh":"龙"},{"en":"forest","zh":"森林"},{"en":"gold","zh":"金"},{"en":"horse","zh":"马"},{"en":"light","zh":"光"},{"en":"moon","zh":"月亮"},{"en":"pencil","zh":"铅笔"},{"en":"rabbit","zh":"兔子"},{"en":"star","zh":"星星"}]');
const app=document.querySelector('#app'),pick=a=>a[Math.floor(Math.random()*a.length)],scores=()=>JSON.parse(localStorage.arcadeScores||'[]');
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
function saveScore(id,score){let s=scores();s.unshift({id,score,time:new Date().toLocaleString()});localStorage.arcadeScores=JSON.stringify(s.slice(0,100))}
function page(p){if(p==='hall')hall();if(p==='scores')scorePage();if(p==='words')wordPage()}
function hall(){app.innerHTML=`<section class="hero"><div><span class="badge">第一批已可试玩</span><h1>用游戏练英语</h1><p class="muted">从 27 款小游戏中选择一款。首批四款现已完成，其他游戏将按原计划逐批加入。</p></div><div class="panel"><strong>当前词库：</strong>${words.length} 个词<br><span class="muted">可随时在“词库”中替换。</span></div></section><section class="grid">${games.map(g=>`<article class="card"><div class="art" style="--tone:${g[4]?'#365f66':'#55412e'}">${g[3]}</div><div><span class="${g[4]?'ready':'planned'}">${g[4]?'可试玩':'规划中'} · ${g[0]}</span><h3>${g[1]}</h3><p>${g[2]}</p><button ${g[4]?'':'disabled'} onclick="play('${g[0]}')">${g[4]?'开始游戏':'敬请期待'}</button></div></article>`).join('')}</section>`}
function scorePage(){let s=scores();app.innerHTML=`<h1>我的成绩</h1><div class="panel">${s.length?`<table><tr><th>游戏</th><th>得分</th><th>时间</th></tr>${s.map(x=>`<tr><td>${x.id}</td><td>${x.score}</td><td>${x.time}</td></tr>`).join('')}</table>`:'<p class="muted">还没有成绩。去大厅开始第一局吧！</p>'}<br><button onclick="localStorage.removeItem('arcadeScores');scorePage()">清除本机成绩</button></div>`}
hall();
