'use strict';
const Arcade={modules:{},clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),dist:(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rand:(a,b)=>a+Math.random()*(b-a),pick:a=>a[Math.floor(Math.random()*a.length)]};
Arcade.register=(id,create)=>Arcade.modules[id]=create;
Arcade.bowlingScore=function(rolls){let score=0,i=0;for(let f=0;f<10&&i<rolls.length;f++){if(rolls[i]===10){if(i+2>=rolls.length)break;score+=10+rolls[i+1]+rolls[i+2];i++}else {if(i+1>=rolls.length)break;let s=rolls[i]+rolls[i+1];if(s===10){if(i+2>=rolls.length)break;score+=10+rolls[i+2]}else score+=s;i+=2}}return score};
Arcade.dartsHit=function(x,y){const r=Math.hypot(x,y),sectors=[20,1,18,4,13,6,10,15,2,17,3,19,7,16,8,11,14,9,12,5],index=Math.floor(((Math.atan2(x,-y)+Math.PI/20+Math.PI*2)%(Math.PI*2))/(Math.PI/10));if(r>170)return {points:0,double:false,label:'脱靶'};if(r<6.35)return {points:50,double:true,label:'红心 50'};if(r<15.9)return {points:25,double:false,label:'外红心 25'};let n=sectors[index],mult=r>=162?2:r>=99&&r<=107?3:1;return {points:n*mult,double:mult===2,label:`${mult===2?'双倍 ':mult===3?'三倍 ':''}${n}`}};
Arcade.matches=function(board){const set=new Set(),h=board.length,w=board[0].length;for(let r=0;r<h;r++)for(let c=0;c<w;c++){let v=board[r][c];if(v<0)continue;for(let [dr,dc] of [[0,1],[1,0]]){let cells=[],rr=r,cc=c;while(rr<h&&cc<w&&board[rr][cc]===v){cells.push(rr*w+cc);rr+=dr;cc+=dc}if(cells.length>=3)cells.forEach(i=>set.add(i))}}return [...set]};
Arcade.start=function(id,help,actions=[]){const name=games.find(g=>g[0]===id)[1];shell(id,name,`<div class="arcade-mission" id="mission"></div><div class="arcade-screen"><canvas id="arcade-canvas" width="900" height="600" tabindex="0" aria-label="${esc(name)}游戏区域"></canvas><div class="arcade-cover" id="arcade-cover"><h2>${esc(name)}</h2><p>${esc(help)}</p><button class="primary" id="arcade-start">开始游戏</button></div></div><div class="arcade-controls"><div class="arcade-dpad"><button data-key="ArrowUp">↑</button><button data-key="ArrowLeft">←</button><button data-key="ArrowDown">↓</button><button data-key="ArrowRight">→</button></div><div class="arcade-actions">${actions.map(a=>`<button data-key="${a.key}">${esc(a.label)}</button>`).join('')}<button id="arcade-pause">暂停</button></div></div>`,help);
  const canvas=document.querySelector('#arcade-canvas'),ctx=canvas.getContext('2d'),cover=document.querySelector('#arcade-cover');
  const e={id,canvas,ctx,W:900,H:600,keys:new Set(),pressed:new Set(),pointer:{x:450,y:300,down:false,clicked:false},pool:ArcadeRules.normalize(words),score:0,lives:3,level:1,elapsed:0,running:false,paused:false,state:{},update:()=>{},draw:()=>{},tap:null,move:null,release:null};round.arcade=e;e.target=e.pool[0];
  e.mission=t=>{if(round?.arcade===e&&!round.done){const node=document.querySelector('#mission');if(node)node.textContent=t}};e.hud=(extra='')=>{if(round?.arcade===e&&!round.done)updateScore(`得分 ${e.score} · ${extra||`生命 ${e.lives} · 第 ${e.level} 关`}`)};e.end=(win,msg)=>{e.running=false;finish(id,Math.round(e.score),msg||(win?'挑战成功！':'游戏结束'),win)};e.hit=()=>{if(e.invincible>0)return;e.lives--;e.invincible=1.8;if(e.lives<=0)e.end(false);e.hud()};e.nextWord=()=>e.target=Arcade.pick(e.pool);
  e.text=(text,x,y,size=20,color='#edf3ff',align='center')=>{ctx.fillStyle=color;ctx.font=`bold ${size}px system-ui`;ctx.textAlign=align;ctx.fillText(text,x,y)};
  e.rect=(x,y,w,h,color,rad=0)=>{ctx.fillStyle=color;if(rad){ctx.beginPath();ctx.roundRect(x,y,w,h,rad);ctx.fill()}else ctx.fillRect(x,y,w,h)};
  e.circle=(x,y,r,color)=>{ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()};
  e.word=(w,x,y,color='#f7c775')=>{let text=typeof w==='string'?w:w.en,width=Math.max(40,text.length*13+16);e.rect(x-width/2,y-17,width,34,color,8);e.text(text,x,y+7,19,'#11223b')};
  // Preserve every letter even on small objects. The DOM reader stays readable on phones.
  e.labels=[];
  e.label=(w,x,y,width=60,size=14,color='#17243b')=>{const text=typeof w==='string'?w:w.en;ctx.save();ctx.font=`600 ${size}px "Segoe UI",sans-serif`;ctx.textAlign='center';ctx.fillStyle=color;const measured=ctx.measureText(text).width;ctx.translate(x,y);ctx.scale(Math.min(1,width/Math.max(1,measured)),1);ctx.fillText(text,0,0);ctx.restore();e.labels.push({text,x,y,word:typeof w==='string'?e.pool.find(p=>p.en===w):w})};
  if(['G04','G05','G07','G08','G09','G10','G11','G12','G13','G17','G23','G24','G25','G27','G28'].includes(id)){
    const panel=document.createElement('section');panel.className='word-reader';panel.innerHTML='<div class="word-reader-focus" aria-live="polite">指向或触碰游戏中的词汇，可在这里放大查看完整拼写</div><div class="word-reader-list"></div>';document.querySelector('.arcade-screen').after(panel);
    const list=panel.querySelector('.word-reader-list'),focus=panel.querySelector('.word-reader-focus'),palette=['#f0b75b','#76c9a4','#8db7ef','#ec89b5'];
    (id==='G07'?e.pool.slice(0,4):id==='G05'?e.pool.slice(0,5):e.pool).forEach((w,i)=>{const chip=document.createElement('span');chip.className='word-reader-chip';if(id==='G07')chip.style.setProperty('--word-color',palette[i]);const en=document.createElement('strong');en.textContent=w.en;const zh=document.createElement('span');zh.textContent=w.zh;chip.append(en,zh);list.append(chip)});
    const read=ev=>{const r=canvas.getBoundingClientRect(),p={x:(ev.clientX-r.left)/r.width*900,y:(ev.clientY-r.top)/r.height*600};let nearest=null,distance=Infinity;for(const label of e.labels){const d=Math.hypot(label.x-p.x,label.y-5-p.y);if(d<distance){nearest=label;distance=d}}if(nearest&&distance<48)focus.textContent=nearest.text+(nearest.word?.zh?' · '+nearest.word.zh:'')};on(canvas,'pointermove',read);on(canvas,'pointerdown',read);
  }
  e.player=(x,y,color='#64e7bd')=>{if(e.invincible>0&&Math.floor(e.elapsed*12)%2)return;e.circle(x,y-11,10,color);e.rect(x-11,y,22,22,color,4);e.rect(x-13,y+19,8,12,color);e.rect(x+5,y+19,8,12,color)};
  function toggle(){if(!e.running||round.done)return;e.paused=!e.paused;e.keys.clear();e.pressed.clear();e.pointer.down=false;cover.hidden=!e.paused;cover.innerHTML='<h2>已暂停</h2><p>点击“继续”或按 P。</p>';document.querySelector('#arcade-pause').textContent=e.paused?'继续':'暂停'}
  on(document.querySelector('#arcade-start'),'click',()=>{e.running=true;cover.hidden=true;canvas.focus()});on(document.querySelector('#arcade-pause'),'click',toggle);
  const valid=new Set(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','z','x','a','d','p','Enter']);on(window,'keydown',ev=>{let k=ev.key.length===1?ev.key.toLowerCase():ev.key;if(!valid.has(k))return;ev.preventDefault();if(k==='p'){if(!ev.repeat)toggle();return}if(!e.keys.has(k))e.pressed.add(k);e.keys.add(k)});on(window,'keyup',ev=>e.keys.delete(ev.key.length===1?ev.key.toLowerCase():ev.key));on(window,'blur',()=>{e.keys.clear();if(e.running&&!e.paused&&!round.done)toggle()});
  document.querySelectorAll('[data-key]').forEach(b=>{let k=b.dataset.key;on(b,'pointerdown',ev=>{ev.preventDefault();b.setPointerCapture(ev.pointerId);e.keys.add(k);e.pressed.add(k)});on(b,'pointerup',()=>e.keys.delete(k));on(b,'pointercancel',()=>e.keys.delete(k))});
  function pos(ev){let r=canvas.getBoundingClientRect();return {x:(ev.clientX-r.left)/r.width*900,y:(ev.clientY-r.top)/r.height*600}}on(canvas,'pointerdown',ev=>{ev.preventDefault();canvas.setPointerCapture(ev.pointerId);Object.assign(e.pointer,pos(ev),{down:true,clicked:true});if(e.running&&!e.paused&&!round.done)e.tap?.(e.pointer,ev)});on(canvas,'pointermove',ev=>{let old={...e.pointer};Object.assign(e.pointer,pos(ev));if(e.running&&!e.paused&&!round.done)e.move?.(e.pointer,old)});on(canvas,'pointerup',ev=>{e.pointer.down=false;if(e.running&&!e.paused&&!round.done)e.release?.(e.pointer,ev)});on(canvas,'pointercancel',()=>{e.pointer.down=false});
  if(globalThis.ArcadeVisual)ArcadeVisual.attach(e);
  let last=performance.now();function frame(t){if(!round||round.arcade!==e)return;let dt=Math.min(.035,(t-last)/1000);last=t;if(e.running&&!e.paused&&!round.done){e.elapsed+=dt;e.invincible=Math.max(0,(e.invincible||0)-dt);e.update(dt);e.pressed.clear();e.pointer.clicked=false}ctx.clearRect(0,0,900,600);e.rect(0,0,900,600,'#101c33');e.draw();if(!round.done)round.frame=requestAnimationFrame(frame)}round.frame=requestAnimationFrame(frame);e.hud();return e;
};
