/* Classic mechanics, shared round lifecycle, keyboard and touch controls. */
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let round=null;
function stopRound(){if(round){round.abort.abort();round.jobs.forEach(clearTimeout);cancelAnimationFrame(round.frame);round=null}}
function beginRound(id){stopRound();round={id,abort:new AbortController(),jobs:[],frame:0,done:false,start:performance.now()};return round}
function on(target,event,fn){target.addEventListener(event,fn,{signal:round.abort.signal})}
function later(fn,ms){let r=round;const t=setTimeout(()=>{if(round===r&&!r.done)fn()},ms);r.jobs.push(t);return t}
function updateScore(text){document.querySelector('#score').textContent=text}
const oldHall=hall;
hall=function(){stopRound();oldHall()};
const oldScores=scorePage;
scorePage=function(){stopRound();oldScores()};
shell=function(id,title,content,help){app.innerHTML=`<div class="round-toolbar"><button onclick="hall()">← 大厅</button><button onclick="play('${id}')">重新开始</button><button onclick="wordPage()">更换词库</button></div><div class="layout"><section class="panel play-panel"><div class="gamebar"><span>${id} · ${title}</span><strong id="score">准备就绪</strong></div><div class="stage">${content}</div></section><aside class="panel side"><h3>玩法说明</h3><p>${help}</p><p>词库：${words.length} 个词</p></aside></div>`};
finish=function(id,score,message){if(!round||round.done)return;round.done=true;round.jobs.forEach(clearTimeout);cancelAnimationFrame(round.frame);saveScore(id,score);const box=document.createElement('div');box.className='result-banner';box.setAttribute('role','status');box.innerHTML=`<h2>${esc(message)}</h2><p>得分 ${score} · 用时 ${Math.round((performance.now()-round.start)/1000)} 秒</p><button class="primary" onclick="play('${id}')">再来一局</button> <button onclick="hall()">返回大厅</button>`;document.querySelector('.stage').append(box)};
play=function(id){if(!games.some(g=>g[0]===id&&g[4]))return;beginRound(id);({G02:crossword,G03:memory,G06:wordSearch,G19:catchGame})[id]()};
function memory(){let pool=ArcadeRules.shuffle(ArcadeRules.normalize(words)).slice(0,8),cards=ArcadeRules.shuffle(pool.flatMap(w=>[{text:w.en,key:w.en},{text:w.zh,key:w.en}])),open=[],matched=new Set(),moves=0,locked=false;
  shell('G03','中英文翻翻乐',`<h2>记住位置，翻出一对</h2><p class="muted">每次翻两张。中英文匹配的卡片保留，不匹配则翻回。</p><div class="memory classic-memory">${cards.map((w,i)=>`<button class="memory-card" data-i="${i}" aria-label="背面卡片 ${i+1}"><span class="card-back">?</span><span class="card-face">${esc(w.text)}</span></button>`).join('')}</div>`,'保留经典翻牌规则：一次只能翻两张，失败后恢复背面，成功后保持正面。通过记忆位置完成整盘。');
  const buttons=[...document.querySelectorAll('.memory-card')];function hud(){updateScore(`配对 ${matched.size}/${pool.length} · 翻牌 ${moves} 次`)}hud();buttons.forEach((b,i)=>on(b,'click',()=>{if(round.done||locked||matched.has(cards[i].key)||open.includes(i))return;b.classList.add('open');b.setAttribute('aria-label',cards[i].text);open.push(i);if(open.length<2)return;moves++;locked=true;hud();later(()=>{let [a,c]=open;if(cards[a].key===cards[c].key){matched.add(cards[a].key);[a,c].forEach(i=>{buttons[i].classList.add('matched');buttons[i].disabled=true})}else open.forEach(i=>{buttons[i].classList.remove('open');buttons[i].setAttribute('aria-label',`背面卡片 ${i+1}`)});open=[];locked=false;hud();if(matched.size===pool.length)finish('G03',Math.max(pool.length*10,pool.length*100-(moves-pool.length)*20),'全部配对成功！')},750)}));
}
function wordSearch(){const puzzle=ArcadeRules.search(words),found=new Set();let start=null,selection=[];
  shell('G06','单词找找看',`<h2>沿一条直线找出单词</h2><p class="muted">横向、纵向、斜向均有，正反方向都有效。拖动划词，或依次点起点和终点。</p><div class="wordlist">${puzzle.entries.map((e,i)=>`<span data-word="${i}">${esc(e.en)} <small>${esc(e.zh)}</small></span>`).join('')}</div><div class="search classic-search" style="--size:${puzzle.size}" role="group" aria-label="找词字母网格">${puzzle.grid.flatMap((row,r)=>row.map((ch,c)=>`<button data-r="${r}" data-c="${c}" aria-label="第 ${r+1} 行第 ${c+1} 列 ${ch}">${ch}</button>`)).join('')}</div><p id="selection-hint" role="status">选一个字母开始。</p>`,'经典找词：从完整的随机字母网格中划出隐藏单词。只能选择连续的直线，不允许跳格或拐弯，已找到的单词可与其他词共享字母。');
  const board=document.querySelector('.search'),hint=document.querySelector('#selection-hint'),cells=[...board.children],at=p=>cells[p.r*puzzle.size+p.c];function hud(){updateScore(`已找到 ${found.size}/${puzzle.entries.length}`)}hud();
  function preview(end){cells.forEach(b=>b.classList.remove('sel'));selection=ArcadeRules.line(start,end);selection.forEach(p=>at(p).classList.add('sel'));hint.textContent=selection.length?selection.map(p=>puzzle.grid[p.r][p.c]).join(''):'请沿横、竖或斜向直线选择。'}
  function commit(){let text=selection.map(p=>puzzle.grid[p.r][p.c]).join(''),idx=puzzle.entries.findIndex((e,i)=>!found.has(i)&&(e.en===text||e.en===[...text].reverse().join('')));if(idx>=0){found.add(idx);selection.forEach(p=>at(p).classList.add('found'));document.querySelector(`[data-word="${idx}"]`).classList.add('done');hint.textContent=`找到 ${puzzle.entries[idx].en}！`;hud()}else hint.textContent='这条线不是尚未找到的单词，再试试。';cells.forEach(b=>b.classList.remove('sel'));start=null;selection=[];if(found.size===puzzle.entries.length)finish('G06',found.size*100,'全部找到了！')}
  let down=false,dragged=false,second=false;function coordinate(e){let b=document.elementFromPoint(e.clientX,e.clientY)?.closest('.classic-search button');return b&&board.contains(b)?{r:+b.dataset.r,c:+b.dataset.c}:null}
  on(board,'pointerdown',e=>{if(round.done)return;const p=coordinate(e);if(!p)return;e.preventDefault();down=true;dragged=false;second=!!start;if(!start)start=p;preview(p);board.setPointerCapture(e.pointerId)});
  on(board,'pointermove',e=>{if(!down||!start)return;let p=coordinate(e);if(p){if(p.r!==start.r||p.c!==start.c)dragged=true;preview(p)}});
  on(board,'pointerup',()=>{if(!down)return;down=false;if(dragged||second)commit()});on(board,'pointercancel',()=>{down=false;start=null;cells.forEach(b=>b.classList.remove('sel'))});
  cells.forEach(b=>on(b,'click',e=>{if(e.detail!==0||round.done)return;let p={r:+b.dataset.r,c:+b.dataset.c};if(start){preview(p);commit()}else {start=p;preview(p)}}));
}
function crossword(){const puzzle=ArcadeRules.crossword(words);if(puzzle.entries.length<2){shell('G02','纵横填字','<h2>这些词暂时无法组成交叉网格</h2><p>请在词库中增加有相同字母的单词，例如 apple、plane、pencil。</p>','单词需要共享至少一个字母才能纵横交叉。');return}
  let selected=puzzle.entries[0],active=selected.cells[0];const values=new Map(),key=p=>p.r+','+p.c;const starts=new Map(puzzle.entries.map(e=>[key({r:e.r,c:e.c}),e.number]));
  shell('G02','纵横填字',`<h2>纵横交叉，共享字母</h2><div class="cross-current" id="current-clue"></div><div class="cross-scroll"><div class="cross classic-cross" style="--cols:${puzzle.cols}">${puzzle.grid.flatMap((row,r)=>row.map((ch,c)=>ch?`<label class="cross-square" data-cell="${r},${c}"><small>${starts.get(`${r},${c}`)||''}</small><input maxlength="1" class="cell" data-r="${r}" data-c="${c}" aria-label="第 ${r+1} 行第 ${c+1} 列" autocomplete="off" autocapitalize="off" spellcheck="false"></label>`:'<div class="cross-block"></div>')).join('')}</div></div><div class="cross-clues">${['across','down'].map(axis=>`<section><h3>${axis==='across'?'横向 →':'纵向 ↓'}</h3>${puzzle.entries.filter(e=>e.axis===axis).sort((a,b)=>a.number-b.number).map(e=>`<button data-entry="${puzzle.entries.indexOf(e)}">${e.number}. ${esc(e.zh)}（${e.en.length}）</button>`).join('')}</section>`).join('')}</div><button id="check" class="primary">检查答案</button> <button id="direction">切换横 / 纵</button><p id="result" role="status"></p>${puzzle.omitted.length?`<p class="muted">本盘 ${puzzle.entries.length} 个相互交叉的词。另有 ${puzzle.omitted.length} 个词未能拼入本盘。</p>`:''}`,'依据横向和纵向线索填入单词。交叉格由两个单词共享；点击线索切换单词，连续输入自动前进。方向键移动，空格或交叉格重复点击切换方向，退格删除。');
  const inputs=[...document.querySelectorAll('.classic-cross input')],bykey=new Map(inputs.map(b=>[key({r:+b.dataset.r,c:+b.dataset.c}),b]));function select(entry,p,focus=true){selected=entry;active=p||entry.cells[0];document.querySelectorAll('.cross-square').forEach(b=>{b.classList.toggle('word-active',selected.cells.some(p=>key(p)===b.dataset.cell));b.classList.toggle('cell-active',b.dataset.cell===key(active))});document.querySelectorAll('[data-entry]').forEach(b=>b.classList.toggle('clue-active',puzzle.entries[+b.dataset.entry]===selected));document.querySelector('#current-clue').textContent=`${entry.number} ${entry.axis==='across'?'横向 →':'纵向 ↓'} · ${entry.zh}（${entry.en.length} 个字母）`;if(focus)bykey.get(key(active)).focus()}
  function toggle(){let options=puzzle.entries.filter(e=>e.cells.some(p=>key(p)===key(active)));select(options.find(e=>e!==selected)||selected,active)}
  function step(delta){let i=selected.cells.findIndex(p=>key(p)===key(active));if(selected.cells[i+delta])select(selected,selected.cells[i+delta])}
  function check(auto=false){let right=inputs.filter(b=>b.value.toLowerCase()===puzzle.grid[+b.dataset.r][+b.dataset.c].toLowerCase()).length;updateScore(`已填 ${inputs.filter(b=>b.value).length}/${inputs.length} 格`);if(right===inputs.length){inputs.forEach(b=>b.disabled=true);finish('G02',puzzle.entries.length*100,'纵横填字完成！')}else if(!auto){inputs.forEach(b=>b.parentElement.classList.toggle('incorrect',!!b.value&&b.value.toLowerCase()!==puzzle.grid[+b.dataset.r][+b.dataset.c].toLowerCase()));document.querySelector('#result').textContent='已标出不正确的字母。空格还需要继续填写。'}}
  inputs.forEach(b=>{let p={r:+b.dataset.r,c:+b.dataset.c};on(b,'click',()=>{if(round.done)return;if(key(active)===key(p))toggle();else select(puzzle.entries.find(e=>e.axis===selected.axis&&e.cells.some(x=>key(x)===key(p)))||puzzle.entries.find(e=>e.cells.some(x=>key(x)===key(p))),p)});on(b,'input',()=>{const letter=b.value.replace(/[^a-z]/ig,'');const expected=puzzle.grid[p.r][p.c];b.value=expected===expected.toUpperCase()?letter.toUpperCase():letter.toLowerCase();values.set(key(p),b.value);b.parentElement.classList.remove('incorrect');if(b.value)step(1);check(true)});on(b,'keydown',e=>{if(round.done)return;if(e.key===' '){e.preventDefault();toggle()}else if(e.key==='Backspace'){e.preventDefault();if(!b.value)step(-1);let input=bykey.get(key(active));input.value='';input.parentElement.classList.remove('incorrect');check(true)}else if(e.key==='Tab'){e.preventDefault();let i=puzzle.entries.indexOf(selected);select(puzzle.entries[(i+(e.shiftKey?-1:1)+puzzle.entries.length)%puzzle.entries.length])}else if(e.key.startsWith('Arrow')){e.preventDefault();let dr=e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0,dc=e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0,np={r:p.r+dr,c:p.c+dc};if(bykey.has(key(np)))select(puzzle.entries.find(x=>x.axis===(dr?'down':'across')&&x.cells.some(t=>key(t)===key(np)))||selected,np)}})});
  document.querySelectorAll('[data-entry]').forEach(b=>on(b,'click',()=>{if(!round.done)select(puzzle.entries[+b.dataset.entry])}));on(document.querySelector('#direction'),'click',()=>{if(!round.done)toggle()});on(document.querySelector('#check'),'click',()=>{if(!round.done)check()});select(selected,active,false);updateScore(`已填 0/${inputs.length} 格`);
}
function catchGame(){let pool=ArcadeRules.normalize(words),target=pool[0],objects=[],score=0,lives=3,combo=0,level=1,x=450,elapsed=0,spawn=0,running=false,paused=false,last=0;const keys=new Set();
  shell('G19','单词接接乐',`<h2 id="catch-target">目标：${esc(target.zh)} · ${esc(target.en)}</h2><p class="muted">左右移动接住目标，避开错误单词和炸弹。漏接目标或接错会损失一条生命。</p><div class="catch-canvas-wrap"><canvas id="catch-canvas" width="900" height="520" tabindex="0" aria-label="接词游戏：方向键左右移动，空格暂停"></canvas><div class="catch-overlay" id="catch-overlay"><h2>准备好接住单词了吗？</h2><p>3 条生命 · 连击加分 · 难度逐渐提高</p><button class="primary" id="catch-start">开始游戏</button></div></div><div class="catch-controls"><button id="catch-left" aria-label="向左移动">◀ 左</button><button id="catch-pause">暂停</button><button id="catch-right" aria-label="向右移动">右 ▶</button></div>`,'保留落物接取的街机规则：单词从上方连续下落，篮子在底部横向移动，在接触时判定。三条生命，漏接目标、接错或碰炸弹扣命；连续接对提高奖励，随着时间推移加速。鼠标、触屏拖动或键盘左右键移动，空格暂停。');
  const canvas=document.querySelector('#catch-canvas'),ctx=canvas.getContext('2d'),overlay=document.querySelector('#catch-overlay');
  function hud(){updateScore(`得分 ${score} · 生命 ${'♥'.repeat(lives)} · 第 ${level} 级`);document.querySelector('#catch-target').textContent=`目标：${target.zh} · ${target.en}  ${combo>1?'连击 ×'+combo:''}`}
  function lose(){lives--;combo=0;if(lives<=0){running=false;finish('G19',score,'游戏结束')}hud()}
  function draw(){ArcadeVisual.drawCatch(ctx,{objects,x,target,elapsed})}
  function tick(t){let dt=Math.min((t-last)/1000||0,.04);last=t;if(running&&!paused&&!round.done){elapsed+=dt;spawn-=dt;level=1+Math.floor(elapsed/20);if(keys.has('ArrowLeft')||keys.has('a'))x-=470*dt;if(keys.has('ArrowRight')||keys.has('d'))x+=470*dt;x=Math.max(58,Math.min(842,x));if(spawn<=0){const bomb=Math.random()<.1,word=Math.random()<.55?target:pool[Math.floor(Math.random()*pool.length)],width=bomb?44:Math.max(76,word.en.length*15+22);objects.push({x:width/2+Math.random()*(900-width),y:-25,width,word,bomb,speed:100+level*20+Math.random()*20});spawn=Math.max(.45,1.2-level*.07)}
      for(const o of objects){let before=o.y;o.y+=o.speed*dt;if(before+19<440&&o.y+19>=440&&Math.abs(o.x-x)<o.width/2+45){o.remove=true;if(o.bomb||o.word.en!==target.en)lose();else {combo++;score+=10+Math.min(combo-1,5)*5;target=pool[Math.floor(Math.random()*pool.length)];hud()}}else if(o.y>520){o.remove=true;if(!o.bomb&&o.word.en===target.en)lose()}if(round.done)break}objects=objects.filter(o=>!o.remove)}draw();if(!round.done)round.frame=requestAnimationFrame(tick)}
  function togglePause(){if(!running||round.done)return;paused=!paused;keys.clear();overlay.hidden=!paused;overlay.innerHTML='<h2>已暂停</h2><p>点击下方“继续”或按空格。</p>';document.querySelector('#catch-pause').textContent=paused?'继续':'暂停'}
  on(document.querySelector('#catch-start'),'click',()=>{running=true;overlay.hidden=true;canvas.focus();last=performance.now()});on(document.querySelector('#catch-pause'),'click',togglePause);
  on(window,'keydown',e=>{if(['ArrowLeft','ArrowRight',' ','a','d'].includes(e.key)){e.preventDefault();if(e.key===' '){if(!e.repeat)togglePause()}else keys.add(e.key)}});on(window,'keyup',e=>keys.delete(e.key));on(window,'blur',()=>{keys.clear();if(running&&!paused)togglePause()});
  let dragging=false;function pointer(e){const rect=canvas.getBoundingClientRect();x=Math.max(58,Math.min(842,(e.clientX-rect.left)/rect.width*900))}on(canvas,'pointerdown',e=>{dragging=true;canvas.setPointerCapture(e.pointerId);pointer(e)});on(canvas,'pointermove',e=>{if(dragging||e.pointerType==='mouse')pointer(e)});on(canvas,'pointerup',()=>dragging=false);on(canvas,'pointercancel',()=>dragging=false);
  [['catch-left','ArrowLeft'],['catch-right','ArrowRight']].forEach(([id,key])=>{let b=document.getElementById(id);on(b,'pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(key)});on(b,'pointerup',()=>keys.delete(key));on(b,'pointercancel',()=>keys.delete(key))});hud();draw();round.frame=requestAnimationFrame(tick);
}
wordPage=function(){stopRound();app.innerHTML=`<h1>词库</h1><div class="panel"><p>每行输入“英文,中文”。支持 2–16 个英文字母的单词，至少 4 个不同的词。</p><textarea id="words" spellcheck="false">${esc(words.map(w=>w.en+','+w.zh).join('\n'))}</textarea><p><button class="primary" id="save">保存词库</button> <span id="msg" role="status"></span></p><p class="muted">填字网格会选取能相互交叉的词。找词每盘最多 8 个，翻牌每盘最多 8 对。</p></div>`;document.querySelector('#save').onclick=()=>{const lines=document.querySelector('#words').value.trim().split(/\r?\n/),parsed=[];for(let i=0;i<lines.length;i++){let [en,...zh]=lines[i].split(/[,，]/);en=en.trim();let meaning=zh.join(',').trim();if(!/^[a-z]{2,16}$/i.test(en)||!meaning){document.querySelector('#msg').textContent=`第 ${i+1} 行格式不正确，请填写 2–16 个英文字母和中文意思。`;return}parsed.push({en:en.toLowerCase(),zh:meaning})}let clean=ArcadeRules.normalize(parsed);if(clean.length<4){document.querySelector('#msg').textContent='至少需要 4 个不同的有效单词。';return}words=clean.map(w=>({...w,en:w.en.toLowerCase()}));localStorage.arcadeWords=JSON.stringify(words);document.querySelector('#msg').textContent=`已保存 ${words.length} 个词。`}};
