Arcade.register('G04',()=>{
 const e=Arcade.start('G04','钩子自动摆动，按空格或点画面放钩。抓到物品后收回，越重越慢；达到金额目标进入下一关，共 3 关。炸药可丢弃正在拉取的物品。',[{key:' ',label:'放钩'},{key:'x',label:'炸药'}]);
 let items=[],angle=.7,length=35,phase='swing',cargo=null,time=60,goal=500,levelMoney=0,bombs=3;
 function setup(){items=[];for(let i=0;i<18;i++)items.push({x:Arcade.rand(60,840),y:Arcade.rand(210,550),r:Arcade.rand(18,32),rock:i%4===0,word:Arcade.pick(e.pool)});e.nextWord();e.mission(`第 ${e.level} 关：本关 $${goal}　词汇加奖：${e.target.zh} · ${e.target.en}`)}setup();
 const tip=()=>({x:450+Math.sin(angle)*length,y:95+Math.cos(angle)*length});function fire(){if(phase==='swing')phase='extend'}e.tap=fire;
 e.update=dt=>{time-=dt;if(time<=0){if(levelMoney>=goal){if(e.level===3){e.end(true,'三关淘金完成！');return}e.level++;goal+=300;levelMoney=0;time=60;phase='swing';cargo=null;length=35;setup()}else {e.end(false,'未达到本关金额目标');return}}if(e.pressed.has(' '))fire();if(e.pressed.has('x')&&cargo&&bombs>0){bombs--;items=items.filter(i=>i!==cargo);cargo=null;phase='retract'}if(phase==='swing')angle=Math.sin(e.elapsed*1.5)*1.25;else if(phase==='extend'){length+=360*dt;let p=tip();cargo=items.find(i=>!i.taken&&Arcade.dist(i,p)<i.r+8);if(cargo){cargo.taken=true;phase='retract'}if(p.x<20||p.x>880||p.y>580)phase='retract'}else {length-=dt*(cargo?(cargo.rock?70:150-cargo.r*2):410);if(length<=35){if(cargo){let value=cargo.rock?20:Math.round(cargo.r*5)+(cargo.word.en===e.target.en?150:0);levelMoney+=value;e.score+=value;items=items.filter(i=>i!==cargo);cargo=null}length=35;phase='swing'}}e.hud(`$${levelMoney}/${goal} · ${Math.ceil(time)} 秒 · 炸药 ${bombs}`)};
 e.draw=()=>{e.rect(0,130,900,470,'#4a392d');e.rect(0,130,900,15,'#8c7140');e.player(450,59);for(const i of items){if(i.taken)continue;e.circle(i.x,i.y,i.r,i.rock?'#8f969e':'#f2c35c');e.label(i.rock?'岩石':i.word,i.x,i.y+5,i.r*2-4,14,'#282c38')}let p=tip();e.ctx.strokeStyle='#eee2bc';e.ctx.lineWidth=3;e.ctx.beginPath();e.ctx.moveTo(450,95);e.ctx.lineTo(p.x,p.y);e.ctx.stroke();e.text('⋃',p.x,p.y+12,30);if(cargo){e.circle(p.x,p.y+17,cargo.r,cargo.rock?'#8f969e':'#f2c35c');e.label(cargo.word,p.x,p.y+22,cargo.r*2,14,'#232e3e')}e.text('金额达标后等待倒计时结束进入下一关',450,27,16)};e.state={get items(){return items},get phase(){return phase},tip};
});
Arcade.register('G08',()=>{
 const e=Arcade.start('G08','左右移动抓爪，对准目标后按抓取。抓爪下降、合拢、提起并送至左侧出口；抓偏会落空。5 次机会中抓中 3 个目标获胜。',[{key:' ',label:'抓取'}]);
 let x=450,y=110,phase='move',cargo=null,tries=5,won=0,items=Array.from({length:14},(_,i)=>({x:80+i%7*120,y:425+Math.floor(i/7)*85,word:e.pool[i%e.pool.length],r:35}));function target(){const accessible=items.filter(i=>!items.some(j=>j!==i&&Math.abs(j.x-i.x)<28&&j.y<i.y));e.target=Arcade.pick(accessible).word;e.mission(`请抓：${e.target.zh} · ${e.target.en}　已抓中 ${won}/3`)}target();
 function grab(){if(phase==='move'&&tries>0){tries--;phase='down'}}e.tap=p=>{if(phase==='move'){x=Arcade.clamp(p.x,55,845);grab()}};e.move=p=>{if(phase==='move'&&e.pointer.down)x=Arcade.clamp(p.x,55,845)};
 e.update=dt=>{if(phase==='move'){x+=((e.keys.has('ArrowRight')?1:0)-(e.keys.has('ArrowLeft')?1:0))*250*dt;x=Arcade.clamp(x,55,845);if(e.pressed.has(' '))grab()}else if(phase==='down'){y+=220*dt;let hit=items.find(i=>Math.abs(i.x-x)<28&&Math.abs(i.y-y)<25);if(hit){cargo=hit;items=items.filter(i=>i!==hit);phase='up'}else if(y>545)phase='up'}else if(phase==='up'){y-=130*dt;if(y<=110){y=110;phase=cargo?'deliver':'return'}}else if(phase==='deliver'){x-=220*dt;if(x<=65){x=65;phase='drop'}}else if(phase==='drop'){y+=250*dt;if(y>480){if(cargo.word.en===e.target.en){won++;e.score+=200}else e.score+=30;cargo=null;phase='return'}}else {y-=300*dt;if(y<=110){y=110;if(won>=3)e.end(true,'抓取挑战成功！');else if(!tries)e.end(false,'机会用完了');else {phase='move';target()}}}e.hud(`机会 ${tries} · 抓中 ${won}/3`)};
 e.draw=()=>{e.rect(35,30,830,540,'#23374c',15);e.rect(55,53,790,9,'#c4d4e4');e.rect(35,480,95,90,'#101b2c');e.text('出口',80,555,17);for(const i of items){e.circle(i.x,i.y,35,'#c49be3');e.word(i.word,i.x,i.y,'#e8c5f2')}e.ctx.strokeStyle='#d6e5f3';e.ctx.lineWidth=4;e.ctx.beginPath();e.ctx.moveTo(x,60);e.ctx.lineTo(x,y);e.ctx.stroke();e.text(cargo?'⋃':'⋁',x,y+16,54,'#8fe5c6');if(cargo)e.word(cargo.word,x,y+40)};e.state={get phase(){return phase},get items(){return items}};
});
Arcade.register('G09',()=>{
 const e=Arcade.start('G09','按住鼠标或手指划切抛起的水果，避开炸弹。漏掉目标水果扣命，切错扣分；连续一划切中多个有连击奖励。',[{key:' ',label:'键盘切割'}]);
 let fruit=[],spawn=0,trail=[],combo=0;function mission(){e.mission(`切目标水果：${e.target.zh} · ${e.target.en}　炸弹不可切`)}mission();
 function slice(a,b){let hits=0;for(const f of fruit){if(f.cut)continue;let vx=b.x-a.x,vy=b.y-a.y,t=Arcade.clamp(((f.x-a.x)*vx+(f.y-a.y)*vy)/(vx*vx+vy*vy||1),0,1);if(Math.hypot(f.x-a.x-t*vx,f.y-a.y-t*vy)<f.r+8){f.cut=true;if(f.bomb)e.hit();else if(f.word.en===e.target.en){hits++;e.score+=30;e.nextWord();mission()}else e.score=Math.max(0,e.score-10)}}if(hits>1){combo=hits;e.score+=hits*20}e.hud()}
 e.move=(p,old)=>{if(e.pointer.down){trail.push({...p,life:.2});slice(old,p)}};e.tap=p=>{trail=[{...p,life:.2}];slice(p,p)};
 e.update=dt=>{spawn-=dt;if(spawn<=0){spawn=.65;const bomb=Math.random()<.16;fruit.push({x:Arcade.rand(100,800),y:650,vx:Arcade.rand(-100,100),vy:Arcade.rand(-640,-540),r:34,bomb,word:Math.random()<.6?e.target:Arcade.pick(e.pool)})}for(const f of fruit){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=700*dt;if(f.y>680&&f.vy>0&&!f.cut){f.cut=true;if(!f.bomb&&f.word.en===e.target.en)e.hit()}}fruit=fruit.filter(f=>f.y<700&&!f.cut);trail.forEach(p=>p.life-=dt);trail=trail.filter(p=>p.life>0);if(e.pressed.has(' '))slice({x:e.pointer.x-70,y:e.pointer.y},{x:e.pointer.x+70,y:e.pointer.y});if(e.elapsed>=60)e.end(true,'水果挑战完成！')};
 e.draw=()=>{for(const f of fruit){e.circle(f.x,f.y,f.r,f.bomb?'#f16986':'#ecab6e');e.text(f.bomb?'✹':f.word.en,f.x,f.y+6,f.bomb?35:16,'#18243c')}e.ctx.strokeStyle='#b7ffe7';e.ctx.lineWidth=6;e.ctx.beginPath();trail.forEach((p,i)=>i?e.ctx.lineTo(p.x,p.y):e.ctx.moveTo(p.x,p.y));e.ctx.stroke();e.text(`${Math.max(0,60-Math.floor(e.elapsed))} 秒${combo>1?' · 连切 '+combo:''}`,450,40,20)};e.state={get fruit(){return fruit}};
});
Arcade.register('G10',()=>{
 const e=Arcade.start('G10','左右移动小船，按下钩下降；鱼咬钩后按住收线。张力过高或过低都会跑鱼，适时松开再收紧。60 秒内捕到 5 条目标鱼。',[{key:' ',label:'下钩 / 按住收线'}]);
 let x=450,y=120,phase='idle',cargo=null,tension=.45,caught=0,fish=Array.from({length:12},(_,i)=>({x:Arcade.rand(50,850),y:Arcade.rand(230,530),vx:(i%2?1:-1)*Arcade.rand(35,75),word:e.pool[i%e.pool.length]}));function mission(){e.target=Arcade.pick(fish).word;e.mission(`目标鱼：${e.target.zh} · ${e.target.en}　已捕获 ${caught}/5`)}mission();function cast(){if(phase==='idle')phase='down'}e.tap=cast;e.move=p=>{if(phase==='idle')x=Arcade.clamp(p.x,40,860)};
 e.update=dt=>{fish.forEach(f=>{f.x+=f.vx*dt;if(f.x<35||f.x>865)f.vx*=-1});if(phase==='idle'){x+=((e.keys.has('ArrowRight')?1:0)-(e.keys.has('ArrowLeft')?1:0))*220*dt;x=Arcade.clamp(x,40,860);if(e.pressed.has(' '))cast()}else if(phase==='down'){y+=160*dt;let f=fish.find(f=>Math.hypot(f.x-x,f.y-y)<32);if(f){cargo=f;fish=fish.filter(a=>a!==f);tension=.45;phase='reel'}else if(y>=555)phase='up'}else if(phase==='reel'){let pull=e.keys.has(' ')||e.pointer.down;tension+=(pull?.55:-.3)*dt+.1*Math.sin(e.elapsed*6)*dt;y-=(pull?95:10)*dt;if(tension<=0||tension>=1){fish.push({...cargo,x,y});cargo=null;phase='up'}else if(y<=120){if(cargo.word.en===e.target.en){caught++;e.score+=150}else e.score+=30;fish.push({...cargo,x:Arcade.rand(50,850),y:Arcade.rand(250,500)});cargo=null;phase='idle';mission();if(caught>=5)e.end(true,'钓鱼任务完成！')}}else {y-=250*dt;if(y<=120){y=120;phase='idle'}}e.hud(`目标鱼 ${caught}/5 · ${Math.max(0,60-Math.floor(e.elapsed))} 秒`);if(e.elapsed>=60)e.end(caught>=5,'钓鱼时间结束')};
 e.draw=()=>{e.rect(0,140,900,460,'#123f64');e.rect(x-47,77,94,26,'#bb9260',8);e.player(x,49);for(const f of fish){e.ctx.fillStyle='#70cebe';e.ctx.beginPath();e.ctx.ellipse(f.x,f.y,33,17,0,0,Math.PI*2);e.ctx.fill();e.text(f.word.en,f.x,f.y+5,14,'#13233c')}e.ctx.strokeStyle='#eff3ff';e.ctx.beginPath();e.ctx.moveTo(x,80);e.ctx.lineTo(x,y);e.ctx.stroke();e.text('J',x,y+10,24);if(cargo)e.word(cargo.word,x,y+20);if(phase==='reel'){e.rect(240,20,420,20,'#334562',8);e.rect(240+tension*400,15,12,30,'#f7c775');e.text('张力：保持在两端之间 · 按住收线，松开缓和',450,65,17)}};e.state={get phase(){return phase},get fish(){return fish}};
});
Arcade.register('G11',()=>{
 const e=Arcade.start('G11','货物在传送带上移动，把英文货物拖入对应中文分区。也可以选货物后按 1、2、3 对应的方向键（左、下、右）。错分或漏分扣命，分对 20 件完成。',[{key:'z',label:'左分区'},{key:' ',label:'中分区'},{key:'x',label:'右分区'}]);
 const bins=ArcadeRules.shuffle(e.pool).slice(0,3);let boxes=[],selected=null,spawn=0,correct=0;
 function sort(index){if(!selected||index<0||index>=bins.length)return;let ok=selected.word.en===bins[index].en;if(ok){e.score+=50;correct++}else e.hit();boxes=boxes.filter(b=>b!==selected);selected=null;if(correct>=20)e.end(true,'分拣任务完成！');hud()}
 function hud(){e.hud(`分对 ${correct}/20 · 生命 ${e.lives}`);e.mission('把传送带上的英文货物送进对应中文分区')}
 e.tap=p=>{if(p.y>390){sort(Math.floor((p.x-60)/260));return}selected=boxes.find(b=>Math.abs(b.x-p.x)<65&&Math.abs(b.y-p.y)<35)||null};e.release=p=>{if(selected&&p.y>390){let i=Math.floor((p.x-60)/260);if(i>=0&&i<3)sort(i)}};
 e.update=dt=>{spawn-=dt;if(spawn<0){boxes.push({x:-70,y:245,word:Arcade.pick(bins)});spawn=Math.max(.7,2-correct*.04)}for(const b of boxes){b.x+=(65+correct*2)*dt;if(b.x>970){if(selected===b)selected=null;b.remove=true;e.hit()}}boxes=boxes.filter(b=>!b.remove);if(!selected)selected=boxes[0]||null;let i=e.pressed.has('z')||e.pressed.has('ArrowLeft')?0:e.pressed.has(' ')||e.pressed.has('ArrowDown')?1:e.pressed.has('x')||e.pressed.has('ArrowRight')?2:-1;if(i>=0)sort(i)};
 e.draw=()=>{e.rect(0,210,900,80,'#425168');for(let x=0;x<900;x+=38)e.circle(x,290,12,'#1a263a');boxes.forEach(b=>{e.word(b.word,b.x,b.y,b===selected?'#f7c775':'#9cbbe2')});bins.forEach((w,i)=>{e.rect(60+i*260,410,245,135,['#4a7c66','#6c6c96','#9b6e50'][i],12);e.text(w.zh,183+i*260,466,25);e.text(['Z / ←','空格 / ↓','X / →'][i],183+i*260,510,18)});if(e.pointer.down&&selected)e.word(selected.word,e.pointer.x,e.pointer.y)};e.state={bins,get boxes(){return boxes}};hud();
});
Arcade.register('G12',()=>{
 const e=Arcade.start('G12','气球不断升起，点击目标英文气球。点错或漏掉目标扣生命。60 秒内尽量得分；键盘左右移动准星，空格爆破。',[{key:' ',label:'爆破'}]);
 let balloons=[],spawn=0,aim=450;function mission(){e.mission(`爆破：${e.target.zh} · ${e.target.en}`)}mission();function pop(p){let b=[...balloons].reverse().find(b=>Math.hypot(p.x-b.x,(p.y-b.y)*.8)<45);if(!b)return;balloons=balloons.filter(a=>a!==b);if(b.word.en===e.target.en){e.score+=50;e.nextWord();mission()}else e.hit();e.hud()}
 e.tap=pop;e.update=dt=>{spawn-=dt;if(spawn<=0){balloons.push({x:Arcade.rand(65,835),y:650,speed:Arcade.rand(55,90)+e.elapsed,word:Math.random()<.6?e.target:Arcade.pick(e.pool),phase:Math.random()*6});spawn=.75}for(const b of balloons){b.y-=b.speed*dt;b.x+=Math.sin(e.elapsed*2+b.phase)*15*dt;if(b.y<-60){b.remove=true;if(b.word.en===e.target.en)e.hit()}}balloons=balloons.filter(b=>!b.remove);aim=Arcade.clamp(aim+((e.keys.has('ArrowRight')?1:0)-(e.keys.has('ArrowLeft')?1:0))*300*dt,30,870);if(e.pressed.has(' ')){let b=balloons.filter(b=>Math.abs(b.x-aim)<45).sort((a,b)=>a.y-b.y)[0];if(b)pop(b)}if(e.elapsed>=60)e.end(true,'气球挑战完成！')};e.draw=()=>{for(const b of balloons){e.ctx.fillStyle='#b48cde';e.ctx.beginPath();e.ctx.ellipse(b.x,b.y,45,52,0,0,Math.PI*2);e.ctx.fill();e.ctx.strokeStyle='#9bb6cf';e.ctx.beginPath();e.ctx.moveTo(b.x,b.y+52);e.ctx.lineTo(b.x+10,b.y+110);e.ctx.stroke();e.text(b.word.en,b.x,b.y+5,16,'#14243b')}e.text('⌖',aim,560,40,'#70e5ba');e.text(`${60-Math.floor(e.elapsed)} 秒`,450,30,18)};e.state={get balloons(){return balloons}};
});
Arcade.register('G13',()=>{
 const e=Arcade.start('G13','标准十局保龄球：每局最多两球，全倒加后两球，补中加下一球；第十局全倒或补中有奖励球。左右调整出手位置，第一次按投球锁定方向，第二次锁定力量。',[{key:' ',label:'投球 / 锁定力度'}]);
 let rolls=[],frame=1,inFrame=[],phase='aim',aim=450,angle=0,power=.5,ball=null,rollTime=0,pins=[],message='';
 function reset(){pins=Array.from({length:10},(_,i)=>{let row=Math.floor((Math.sqrt(8*i+1)-1)/2),start=row*(row+1)/2,col=i-start;return {x:450+(col-row/2)*36,y:170-row*30,down:false,vx:0,vy:0,word:e.pool[i%e.pool.length]}})}reset();
 function action(){if(phase==='aim'){phase='power';message='再次按投球锁定力度'}else if(phase==='power'){phase='rolling';ball={x:aim,y:535,vx:Math.sin(angle)*(260+power*230),vy:-Math.cos(angle)*(260+power*230),r:16};rollTime=0}}
 e.tap=p=>{if(phase==='aim'){aim=Arcade.clamp(p.x,340,560);angle=Arcade.clamp((p.x-450)/600,-.25,.25)}action()};
 function settle(){let count=pins.filter(p=>p.down).length-(inFrame.length&&frame<10?inFrame[0]:0);if(frame===10&&inFrame.length===1&&inFrame[0]!==10)count=pins.filter(p=>p.down).length-inFrame[0];count=Arcade.clamp(count,0,10);rolls.push(count);inFrame.push(count);message=count===10?'STRIKE!':pins.every(p=>p.down)?'SPARE!':`击倒 ${count} 瓶`;e.score=Arcade.bowlingScore(rolls);
   if(frame<10){if(inFrame[0]===10||inFrame.length===2){frame++;inFrame=[];reset()}}else {let done=inFrame.length===3||(inFrame.length===2&&inFrame[0]+inFrame[1]<10);if(done){e.end(true,`十局完成 · ${e.score} 分`);return}if(pins.every(p=>p.down))reset()}phase='aim';ball=null;hud()}
 function hud(){e.hud(`第 ${frame}/10 局 · 本局 ${inFrame.join(' / ')||'未投'}`);e.mission(`保龄球标准计分 · 球瓶词汇 ${e.pool.slice(0,3).map(w=>w.en+' '+w.zh).join(' / ')}`)}
 e.update=dt=>{if(e.pressed.has(' '))action();if(phase==='aim'){aim=Arcade.clamp(aim+((e.keys.has('ArrowRight')?1:0)-(e.keys.has('ArrowLeft')?1:0))*100*dt,335,565);angle=Math.sin(e.elapsed*1.4)*.18}else if(phase==='power')power=(Math.sin(e.elapsed*3)+1)/2;else {rollTime+=dt;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;for(const p of pins){if(!p.down&&Math.hypot(p.x-ball.x,p.y-ball.y)<28){p.down=true;p.vx=ball.vx*.55+(p.x-ball.x)*9;p.vy=-160-power*200}if(p.down){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;for(const q of pins)if(!q.down&&Math.hypot(p.x-q.x,p.y-q.y)<25){q.down=true;q.vx=p.vx+(q.x-p.x)*6;q.vy=p.vy*.7}}}if(rollTime>2.5)settle()}};
 e.draw=()=>{e.rect(305,35,290,540,'#aa885d');for(let x=315;x<590;x+=25)e.rect(x,35,1,540,'#c9aa77');e.rect(280,35,22,540,'#27354e');e.rect(598,35,22,540,'#27354e');pins.forEach(p=>{if(p.down)return;e.circle(p.x,p.y,12,'#f8f2e9');e.rect(p.x-5,p.y-20,10,18,'#f8f2e9',4);e.rect(p.x-5,p.y-13,10,4,'#ea7393');e.label(p.word,p.x,p.y+27,32,11,'#f3e5cb')});if(ball)e.circle(ball.x,ball.y,16,'#7657a7');else {e.circle(aim,535,16,'#7657a7');e.ctx.strokeStyle='#eff6dd';e.ctx.beginPath();e.ctx.moveTo(aim,520);e.ctx.lineTo(aim+Math.sin(angle)*200,520-Math.cos(angle)*200);e.ctx.stroke()}e.rect(660,170,28,230,'#3b4c63');e.rect(660,400-power*230,28,power*230,'#66d7ad');e.text('力量',675,435,17);e.text(message||'第一按方向 · 第二按力量',450,590,18);e.text(rolls.map(n=>n===10?'X':n).join(' · '),450,24,14)};e.state={get rolls(){return rolls},get pins(){return pins},get phase(){return phase}};hud();
});
Arcade.register('G14',()=>{
 const e=Arcade.start('G14','301 飞镖：每轮 3 镖，分数减到恰好 0 且最后一镖命中双倍区才获胜。超分、剩 1 分或非双倍归零会爆分，本轮分数回退。鼠标 / 手指瞄准，点击投镖。',[{key:' ',label:'投镖'}]);
 let remaining=301,turnStart=301,turn=1,darts=0,base={x:450,y:280},marks=[],message='',cool=0;const center={x:450,y:285},scale=1.35,numbers=[20,1,18,4,13,6,10,15,2,17,3,19,7,16,8,11,14,9,12,5];
 function reticle(){return {x:base.x+Math.sin(e.elapsed*3.4)*11,y:base.y+Math.cos(e.elapsed*2.7)*11}}
 function throwDart(){if(cool>0)return;let p=reticle(),hit=Arcade.dartsHit((p.x-center.x)/scale,(p.y-center.y)/scale);marks.push(p);darts++;let value=remaining-hit.points;message=hit.label;if(value===0&&hit.double){remaining=0;e.score+=500;hud();e.end(true,'双倍收尾，301 清零！');return}if(value<0||value===1||value===0){remaining=turnStart;message+=' · 爆分，回退本轮';darts=3}else {remaining=value;e.score+=hit.points}if(darts===3){turn++;darts=0;turnStart=remaining;if(turn>15){e.end(false,'15 轮结束');return}}cool=.45;hud()}
 function hud(){e.hud(`剩余 ${remaining} · 第 ${turn} 轮 · 本轮 ${darts}/3 镖`);e.mission(`标准 301 · 双倍收尾　词汇：${e.target.en} = ${e.target.zh}`)}
 e.tap=p=>{base={x:p.x,y:p.y};throwDart()};e.move=p=>base={x:p.x,y:p.y};e.update=dt=>{cool=Math.max(0,cool-dt);base.x+=((e.keys.has('ArrowRight')?1:0)-(e.keys.has('ArrowLeft')?1:0))*110*dt;base.y+=((e.keys.has('ArrowDown')?1:0)-(e.keys.has('ArrowUp')?1:0))*110*dt;if(e.pressed.has(' '))throwDart()};
 e.draw=()=>{const ctx=e.ctx;for(let i=0;i<20;i++){let a=-Math.PI/2-Math.PI/20+i*Math.PI/10,b=a+Math.PI/10;for(const [inner,outer]of [[0,99],[99,107],[107,162],[162,170]]){ctx.beginPath();ctx.arc(center.x,center.y,outer*scale,a,b);ctx.arc(center.x,center.y,inner*scale,b,a,true);ctx.closePath();ctx.fillStyle=inner===99||inner===162?(i%2?'#be525a':'#4d9c7d'):(i%2?'#e6ddc6':'#283244');ctx.fill()}let ang=-Math.PI/2+i*Math.PI/10;e.text(numbers[i],center.x+Math.cos(ang)*250,center.y+Math.sin(ang)*250+7,20)}e.circle(center.x,center.y,15.9*scale,'#4d9c7d');e.circle(center.x,center.y,6.35*scale,'#be525a');marks.slice(-3).forEach(p=>e.text('×',p.x,p.y+7,27,'#7aefff'));let p=reticle();e.text('+',p.x,p.y+8,28,'#f7c775');e.text(message,450,580,20)};e.state={get remaining(){return remaining},get turn(){return turn},throwDart};hud();
});
