function mazeGrid(w,h){const grid=Array.from({length:h},()=>Array(w).fill(1));const stack=[[1,1]];grid[1][1]=0;while(stack.length){let [c,r]=stack.at(-1),options=ArcadeRules.shuffle([[2,0],[-2,0],[0,2],[0,-2]]).filter(([dc,dr])=>c+dc>0&&r+dr>0&&c+dc<w-1&&r+dr<h-1&&grid[r+dr][c+dc]);if(!options.length){stack.pop();continue}let [dc,dr]=options[0];grid[r+dr/2][c+dc/2]=0;grid[r+dr][c+dc]=0;stack.push([c+dc,r+dr])}for(let r=2;r<h-1;r++)for(let c=2;c<w-1;c++)if(grid[r][c]&&Math.random()<.15&&((!grid[r-1][c]&&!grid[r+1][c])||(!grid[r][c-1]&&!grid[r][c+1])))grid[r][c]=0;return grid}
Arcade.register('G21',()=>{
 const e=Arcade.start('G21','方向键控制迷宫中的角色，吃完所有豆子通关。四角能量丸让追兵暂时变蓝，此时可以吃掉它们。左右隧道互通；追兵在追逐和巡逻间切换。共 3 关。');
 const W=19,H=15,S=34,ox=127,oy=47,dirs=[[1,0],[-1,0],[0,1],[0,-1]],key=(c,r)=>c+','+r;let grid,dots,power=new Set(),player,ghosts,direction=[1,0],wanted=[1,0],timer=0,ghostTimer=0,fright=0,eaten=0;
 function setup(){grid=mazeGrid(W,H);for(let c=0;c<W;c++)grid[7][c]=0;dots=new Set();for(let r=1;r<H-1;r++)for(let c=1;c<W-1;c++)if(!grid[r][c])dots.add(key(c,r));power=new Set([key(1,1),key(17,1),key(1,13),key(17,13)]);reset();e.nextWord();e.mission(`吃豆通关 · 当前词 ${e.target.en} = ${e.target.zh}　能量丸可反击追兵`)}
 function reset(){player={c:1,r:7};ghosts=Array.from({length:4},(_,i)=>({c:8+i,r:7,home:i,color:['#e9788f','#7fc8e0','#c593e0','#edba74'][i],last:[0,1],dead:0}));e.invincible=2;fright=0}
 function next(c,r,dc,dr){let nc=c+dc,nr=r+dr;if(nr===7)nc=(nc+W)%W;if(nr<0||nr>=H||nc<0||nc>=W||grid[nr][nc])return null;return {c:nc,r:nr}}
 function collide(){for(const g of ghosts)if(!g.dead&&g.c===player.c&&g.r===player.r){if(fright>0){g.dead=2;e.score+=200}else if(!e.invincible){e.hit();reset();break}}}
 e.tap=p=>{let dx=p.x-(ox+player.c*S+S/2),dy=p.y-(oy+player.r*S+S/2);wanted=Math.abs(dx)>Math.abs(dy)?[Math.sign(dx),0]:[0,Math.sign(dy)]};
 e.update=dt=>{fright=Math.max(0,fright-dt);timer+=dt;ghostTimer+=dt;for(const [k,d]of [['ArrowRight',[1,0]],['ArrowLeft',[-1,0]],['ArrowUp',[0,-1]],['ArrowDown',[0,1]]])if(e.keys.has(k))wanted=d;
   if(timer>.12){timer=0;let n=next(player.c,player.r,...wanted);if(n)direction=wanted;else n=next(player.c,player.r,...direction);if(n)Object.assign(player,n);let k=key(player.c,player.r);if(dots.delete(k)){e.score+=10;eaten++;if(eaten%12===0){e.score+=30;e.nextWord();e.mission(`词汇奖励 ${e.target.en} = ${e.target.zh}`)}}if(power.delete(k)){fright=7;ghosts.forEach(g=>g.last=g.last.map(v=>-v))}collide();if(!dots.size){if(e.level>=3){e.end(true,'三关迷宫完成！');return}e.level++;setup()}}
   if(ghostTimer>(fright?.27:Math.max(.15,.24-e.level*.018))){ghostTimer=0;for(const g of ghosts){if(g.dead){g.dead-=.2;if(g.dead<=0){g.c=9;g.r=7}continue}let options=dirs.map(d=>({d,p:next(g.c,g.r,...d)})).filter(o=>o.p),nonreverse=options.filter(o=>o.d[0]!==-g.last[0]||o.d[1]!==-g.last[1]);if(nonreverse.length)options=nonreverse;let scatter=Math.floor(e.elapsed/12)%3===0,target=scatter?{c:g.home%2?17:1,r:g.home<2?1:13}:player;const distances=new Map(),queue=[];let destination=target;if(grid[destination.r]?.[destination.c]!==0){let open=[];for(let rr=1;rr<H-1;rr++)for(let cc=1;cc<W-1;cc++)if(!grid[rr][cc])open.push({c:cc,r:rr});open.sort((a,b)=>Math.abs(a.c-target.c)+Math.abs(a.r-target.r)-Math.abs(b.c-target.c)-Math.abs(b.r-target.r));destination=open[0]}queue.push(destination);distances.set(key(destination.c,destination.r),0);for(let qi=0;qi<queue.length;qi++){let p=queue[qi],distance=distances.get(key(p.c,p.r));for(let d of dirs){let n=next(p.c,p.r,...d);if(n&&!distances.has(key(n.c,n.r))){distances.set(key(n.c,n.r),distance+1);queue.push(n)}}}options.sort((a,b)=>{let da=distances.get(key(a.p.c,a.p.r))??999,db=distances.get(key(b.p.c,b.p.r))??999;return fright?db-da:da-db});if(options.length){Object.assign(g,options[0].p);g.last=options[0].d}}collide()}e.hud(`生命 ${e.lives} · 豆子 ${dots.size} · 第 ${e.level} 关`)};
 e.draw=()=>{for(let r=0;r<H;r++)for(let c=0;c<W;c++){let x=ox+c*S,y=oy+r*S;if(grid[r][c])e.rect(x+2,y+2,S-4,S-4,'#284984',6);else if(dots.has(key(c,r)))e.circle(x+S/2,y+S/2,power.has(key(c,r))?8:3,'#f4dfac')}let x=ox+player.c*S+S/2,y=oy+player.r*S+S/2;e.circle(x,y,13,'#efc66c');e.ctx.fillStyle='#101c33';e.ctx.beginPath();e.ctx.moveTo(x,y);let a=Math.atan2(direction[1],direction[0]),mouth=.2+.15*Math.sin(e.elapsed*18);e.ctx.arc(x,y,14,a-mouth,a+mouth);e.ctx.closePath();e.ctx.fill();ghosts.forEach(g=>{let x=ox+g.c*S+S/2,y=oy+g.r*S+S/2;if(g.dead){e.text('••',x,y+5,17);return}e.circle(x,y,13,fright?'#6999eb':g.color);e.rect(x-13,y,26,13,fright?'#6999eb':g.color);e.circle(x-5,y-2,4,'#fff');e.circle(x+5,y-2,4,'#fff')});e.text(fright>0?`能量 ${Math.ceil(fright)} 秒`:'吃完豆子，守住生命',450,585,18)};e.state={get grid(){return grid},get player(){return player},get ghosts(){return ghosts},get dots(){return dots}};setup();
});
Arcade.register('G24',()=>{
 const e=Arcade.start('G24','方向键驾驶坦克，按住射击。砖墙可打碎，钢墙阻挡，水域不可通行。保护底部基地，击毁本关 12 辆敌车进入下一关，共 3 关；基地被击中立即失败。',[{key:' ',label:'射击'}]);
 const W=21,H=17,S=31,ox=124,oy=34;let map,player,bullets=[],enemies=[],spawn=0,kills=0,spawned=0,fire=0,base={c:10,r:15},drops=[],freeze=0;const dirs=[[0,-1],[1,0],[0,1],[-1,0]];
 function setup(){map=Array.from({length:H},(_,r)=>Array.from({length:W},(_,c)=>r===0||c===0||r===H-1||c===W-1?2:0));for(let r=3;r<13;r++)for(let c=2;c<W-2;c++)if(Math.random()<.25)map[r][c]=Math.random()<.12?2:1;for(let c=8;c<=12;c++)map[14][c]=1;map[15][9]=map[15][11]=1;map[15][10]=4;map[8][5]=map[8][6]=3;player={x:ox+7*S+S/2,y:oy+15*S+S/2,dir:0,upgrade:0};bullets=[];enemies=[];spawned=0;kills=0;drops=[];e.nextWord();e.mission(`保护基地 · 击毁 12 辆敌车　目标词 ${e.target.zh} · ${e.target.en}`)}
 const tile=(x,y)=>({c:Math.floor((x-ox)/S),r:Math.floor((y-oy)/S)});function blocked(x,y){for(let [dx,dy]of [[-11,-11],[11,-11],[-11,11],[11,11]]){let p=tile(x+dx,y+dy);if(!map[p.r]||map[p.r][p.c]!==0)return true}return false}
 function shoot(a,enemy){let d=dirs[a.dir];bullets.push({x:a.x+d[0]*19,y:a.y+d[1]*19,dx:d[0],dy:d[1],enemy,owner:a})}
 e.update=dt=>{freeze=Math.max(0,freeze-dt);spawn-=dt;fire-=dt;if(spawn<0&&spawned<12&&enemies.length<4){let c=[2,10,18][spawned%3];enemies.push({x:ox+c*S+S/2,y:oy+S*1.5,dir:2,timer:0,fire:1.5,word:e.pool[spawned%e.pool.length]});spawned++;spawn=2}let dir=e.keys.has('ArrowUp')?0:e.keys.has('ArrowRight')?1:e.keys.has('ArrowDown')?2:e.keys.has('ArrowLeft')?3:-1;if(dir>=0){player.dir=dir;let d=dirs[dir],nx=player.x+d[0]*140*dt,ny=player.y+d[1]*140*dt;if(!blocked(nx,ny)){player.x=nx;player.y=ny}}if((e.keys.has(' ')||e.pointer.down)&&fire<0&&bullets.filter(b=>!b.enemy).length<(player.upgrade?2:1)){shoot(player,false);fire=.3}
   for(const a of enemies)if(!freeze){a.timer-=dt;a.fire-=dt;let d=dirs[a.dir],nx=a.x+d[0]*70*dt,ny=a.y+d[1]*70*dt;if(blocked(nx,ny)||a.timer<0){a.dir=Math.random()<.5?2:Math.floor(Math.random()*4);a.timer=Arcade.rand(.5,1.5)}else {a.x=nx;a.y=ny}if(a.fire<0){shoot(a,true);a.fire=Arcade.rand(.9,2)}if(Arcade.dist(a,player)<25)e.hit()}
   for(const b of bullets){b.x+=b.dx*(b.enemy?240:360)*dt;b.y+=b.dy*(b.enemy?240:360)*dt;let p=tile(b.x,b.y),t=map[p.r]?.[p.c];if(t===undefined){b.dead=true;continue}if(t===1){map[p.r][p.c]=0;b.dead=true}else if(t===2)b.dead=true;else if(t===4){b.dead=true;e.end(false,'基地被击毁');return}if(b.enemy){if(Arcade.dist(b,player)<19){b.dead=true;e.hit()}}else {let a=enemies.find(a=>Arcade.dist(a,b)<21);if(a){a.dead=true;b.dead=true;kills++;e.score+=a.word.en===e.target.en?200:100;if(Math.random()<.3)drops.push({x:a.x,y:a.y,type:Math.random()<.5?'star':'freeze'})}}}
   for(const b of bullets)if(!b.dead&&bullets.some(a=>a!==b&&a.enemy!==b.enemy&&Arcade.dist(a,b)<10)){b.dead=true}bullets=bullets.filter(b=>!b.dead);enemies=enemies.filter(a=>!a.dead);drops.forEach(d=>{if(Arcade.dist(player,d)<28){if(d.type==='star')player.upgrade=1;else freeze=5;d.dead=true;e.score+=50}});drops=drops.filter(d=>!d.dead);if(kills>=12){if(e.level>=3){e.end(true,'基地守住了，三关完成！');return}e.level++;setup()}e.hud(`生命 ${e.lives} · 敌车 ${kills}/12 · 第 ${e.level} 关`)};
 e.draw=()=>{for(let r=0;r<H;r++)for(let c=0;c<W;c++){let t=map[r][c],x=ox+c*S,y=oy+r*S;if(t===1){e.rect(x+1,y+1,S-2,S-2,'#a86c4c');e.rect(x,y+14,S,2,'#d49b72');e.rect(x+14,y,2,14,'#d49b72')}if(t===2)e.rect(x+1,y+1,S-2,S-2,'#788a9d');if(t===3)e.rect(x,y,S,S,'#4b93bc');if(t===4){e.rect(x+1,y+1,S-2,S-2,'#f0c76f');e.text('基',x+S/2,y+23,20,'#14253b')}}function tank(a,color){e.rect(a.x-14,a.y-14,28,28,color,3);e.circle(a.x,a.y,9,'#1a3041');let d=dirs[a.dir];e.rect(a.x+(d[0]<0?-22:-3),a.y+(d[1]<0?-22:-3),d[0]?25:6,d[1]?25:6,color)}tank(player,'#79e0ba');enemies.forEach(a=>tank(a,'#e7a07e'));bullets.forEach(b=>e.circle(b.x,b.y,3,'#f9f0c0'));drops.forEach(d=>e.word(d.type==='star'?'★':'❄',d.x,d.y))};e.state={get map(){return map},get player(){return player},get enemies(){return enemies},get bullets(){return bullets}};setup();
});
Arcade.register('G25',()=>{
 const e=Arcade.start('G25','在网格中放置炸弹，3 秒后十字爆炸。石柱挡爆炸，木箱可炸毁，炸弹会连锁。捡火力与容量奖励，消灭敌人并找到箱子下的出口。爆炸也会伤到自己。共 3 关。',[{key:' ',label:'放炸弹'}]);
 const W=13,H=11,S=46,ox=151,oy=48,key=(c,r)=>c+','+r;let grid,player,bombs=[],flames=[],enemies=[],drops=[],capacity=1,range=2,moveClock=0,enemyClock=0,exit={c:11,r:9},time=120;const dirs=[[0,-1],[1,0],[0,1],[-1,0]];
 function setup(){grid=Array.from({length:H},(_,r)=>Array.from({length:W},(_,c)=>r===0||c===0||r===H-1||c===W-1||r%2===0&&c%2===0?2:Math.random()<.48?1:0));for(let [c,r]of [[1,1],[2,1],[1,2],[11,1],[10,1],[11,2],[1,9],[2,9],[1,8],[11,9],[10,9],[11,8]])grid[r][c]=0;grid[exit.r][exit.c]=1;player={c:1,r:1};enemies=[{c:11,r:1},{c:1,r:9},{c:11,r:8}];bombs=[];flames=[];drops=[];time=120;e.nextWord();e.mission(`炸箱、击败追兵、走入右下出口 · 词汇 ${e.target.en} = ${e.target.zh}`)}
 function allowed(c,r){return grid[r]?.[c]===0&&!bombs.some(b=>b.c===c&&b.r===r)}
 function place(){if(bombs.length<capacity&&!bombs.some(b=>b.c===player.c&&b.r===player.r))bombs.push({c:player.c,r:player.r,time:3,range})}
 function explode(b){if(b.dead)return;b.dead=true;let cells=[{c:b.c,r:b.r}];for(let [dc,dr]of dirs)for(let n=1;n<=b.range;n++){let c=b.c+dc*n,r=b.r+dr*n,t=grid[r]?.[c];if(t===undefined||t===2)break;cells.push({c,r});if(t===1){grid[r][c]=0;e.score+=15;if(Math.random()<.3&&!(c===exit.c&&r===exit.r))drops.push({c,r,type:Math.random()<.5?'fire':'bomb',word:Arcade.pick(e.pool)});break}}for(const p of cells){flames.push({...p,time:.65});let chain=bombs.find(q=>q!==b&&!q.dead&&q.c===p.c&&q.r===p.r);if(chain)explode(chain)}}
 e.tap=p=>{let c=Math.floor((p.x-ox)/S),r=Math.floor((p.y-oy)/S),dc=c-player.c,dr=r-player.r;if(Math.abs(dc)+Math.abs(dr)===1&&allowed(c,r))Object.assign(player,{c,r});else place()};
 e.update=dt=>{time-=dt;moveClock-=dt;enemyClock-=dt;if(e.pressed.has(' '))place();if(moveClock<=0){let dir=e.keys.has('ArrowUp')?0:e.keys.has('ArrowRight')?1:e.keys.has('ArrowDown')?2:e.keys.has('ArrowLeft')?3:-1;if(dir>=0){let [dc,dr]=dirs[dir],c=player.c+dc,r=player.r+dr;if(allowed(c,r))Object.assign(player,{c,r});moveClock=.12}}for(const b of bombs){b.time-=dt;if(b.time<=0)explode(b)}bombs=bombs.filter(b=>!b.dead);flames.forEach(f=>f.time-=dt);flames=flames.filter(f=>f.time>0);
   if(enemyClock<=0){enemyClock=.38;for(const a of enemies){let options=ArcadeRules.shuffle(dirs).map(([dc,dr])=>({c:a.c+dc,r:a.r+dr})).filter(p=>allowed(p.c,p.r)&&!flames.some(f=>f.c===p.c&&f.r===p.r));options.sort((a,b)=>Math.abs(a.c-player.c)+Math.abs(a.r-player.r)-Math.abs(b.c-player.c)-Math.abs(b.r-player.r));if(options.length)Object.assign(a,Math.random()<.65?options[0]:Arcade.pick(options))}}
   for(const a of enemies)if(flames.some(f=>f.c===a.c&&f.r===a.r)){a.dead=true;e.score+=150}enemies=enemies.filter(a=>!a.dead);if(flames.some(f=>f.c===player.c&&f.r===player.r)||enemies.some(a=>a.c===player.c&&a.r===player.r)){if(!e.invincible){e.hit();player={c:1,r:1}}}drops.forEach(d=>{if(d.c===player.c&&d.r===player.r){if(d.type==='fire')range=Math.min(5,range+1);else capacity=Math.min(4,capacity+1);e.score+=50;d.dead=true}});drops=drops.filter(d=>!d.dead);if(!enemies.length&&grid[exit.r][exit.c]===0&&player.c===exit.c&&player.r===exit.r){if(e.level>=3){e.end(true,'三关炸弹迷宫完成！');return}e.level++;setup()}if(time<=0)e.end(false,'本关时间用完');e.hud(`生命 ${e.lives} · 敌人 ${enemies.length} · 炸弹 ${capacity} / 火力 ${range} · ${Math.ceil(time)} 秒`)};
 e.draw=()=>{for(let r=0;r<H;r++)for(let c=0;c<W;c++){let x=ox+c*S,y=oy+r*S,t=grid[r][c];e.rect(x+1,y+1,S-2,S-2,t===2?'#607087':t===1?'#a47a52':'#234d46',5);if(t===1)e.label(e.pool[(r*W+c)%e.pool.length],x+S/2,y+S/2+4,S-6,13,'#f7dfb1')}if(!grid[exit.r][exit.c]){e.rect(ox+exit.c*S+6,oy+exit.r*S+4,S-12,S-8,enemies.length?'#7d8790':'#f3cb78',6);e.text('门',ox+exit.c*S+S/2,oy+exit.r*S+30,20,'#24354a')}flames.forEach(f=>e.rect(ox+f.c*S+2,oy+f.r*S+2,S-4,S-4,'#f4b154',8));bombs.forEach(b=>{e.circle(ox+b.c*S+S/2,oy+b.r*S+S/2,15,'#182334');e.text(Math.ceil(b.time),ox+b.c*S+S/2,oy+b.r*S+S/2+5,14,'#f9d789')});drops.forEach(d=>e.text(d.type==='fire'?'F':'B',ox+d.c*S+S/2,oy+d.r*S+30,24,'#f7d581'));enemies.forEach(a=>e.circle(ox+a.c*S+S/2,oy+a.r*S+S/2,15,'#e894a3'));e.player(ox+player.c*S+S/2,oy+player.r*S+S/2-7)};e.state={get grid(){return grid},get player(){return player},get bombs(){return bombs},get flames(){return flames},explode};setup();
});
