Arcade.register('G15',()=>{
 const e=Arcade.start('G15','移动磁铁，按住吸附键将附近字母吸向自己，松开字母会继续惯性漂移。按目标顺序吸到字母组成单词，错误字母会弹开。完成 3 个词获胜。',[{key:' ',label:'按住磁吸'}]);
 let player={x:450,y:320},letters=[],index=0,completed=0;function setup(){index=0;letters=[...e.target.en,...'aeiouxyz'].map(ch=>({ch,x:Arcade.rand(70,830),y:Arcade.rand(90,530),vx:Arcade.rand(-20,20),vy:Arcade.rand(-20,20),cool:0}));e.mission(`磁力拼词：${e.target.zh} · ${e.target.en}　先吸 ${e.target.en[0]}`)}setup();e.move=p=>{if(e.pointer.down){player.x=p.x;player.y=p.y}};
 e.update=dt=>{player.x+=((e.keys.has('ArrowRight')?1:0)-(e.keys.has('ArrowLeft')?1:0))*240*dt;player.y+=((e.keys.has('ArrowDown')?1:0)-(e.keys.has('ArrowUp')?1:0))*240*dt;player.x=Arcade.clamp(player.x,30,870);player.y=Arcade.clamp(player.y,70,565);for(const l of letters){l.cool=Math.max(0,l.cool-dt);let d=Arcade.dist(l,player);if((e.keys.has(' ')||e.pointer.down)&&d<180){l.vx+=(player.x-l.x)/(d||1)*400*dt;l.vy+=(player.y-l.y)/(d||1)*400*dt}l.x+=l.vx*dt;l.y+=l.vy*dt;l.vx*=Math.pow(.7,dt);l.vy*=Math.pow(.7,dt);if(l.x<25||l.x>875){l.vx*=-.8;l.x=Arcade.clamp(l.x,25,875)}if(l.y<70||l.y>575){l.vy*=-.8;l.y=Arcade.clamp(l.y,70,575)}if(d<32&&!l.cool){if(l.ch===e.target.en[index]){l.remove=true;index++;e.score+=30;if(index===e.target.en.length){completed++;if(completed>=e.pool.length){e.end(true,'磁力拼词完成！');return}e.nextWord();setup();break}e.mission(`${e.target.zh} · ${e.target.en.slice(0,index)}${'＿'.repeat(e.target.en.length-index)}　下一个 ${e.target.en[index]}`)}else {l.vx=(l.x-player.x)*12;l.vy=(l.y-player.y)*12;l.cool=1;e.score=Math.max(0,e.score-5)}}}letters=letters.filter(l=>!l.remove);e.hud(`完成 ${completed}/${e.pool.length} · ${Math.max(0,90-Math.floor(e.elapsed))} 秒`);if(e.elapsed>=90)e.end(false,'磁吸时间结束')};
 e.draw=()=>{if(e.keys.has(' ')||e.pointer.down)e.circle(player.x,player.y,180,'#4a9e7d22');letters.forEach(l=>{e.circle(l.x,l.y,21,'#f0c477');e.text(l.ch,l.x,l.y+7,23,'#10243b')});e.text('∩',player.x,player.y+15,65,'#7aebc0');e.text(`已完成 ${completed} 个词`,450,35,19)};e.state={player,get letters(){return letters},get index(){return index}};
});
function letterVoyage(id,underwater){
 const e=Arcade.start(id,underwater?'方向键或拖动驾驶潜水员，在氧气耗尽前按顺序收集字母。回到上方水面可以补充氧气；避开水母和暗流。收齐一个词后返回水面交付，共 3 个。':'方向键驾驶飞船，存在惯性，反向推力可以刹车。按顺序收集字母，避开小行星；场地边缘可穿越。完成 3 个词。',[{key:' ',label:underwater?'快速上浮':'刹车'}]);
 let player={x:450,y:underwater?55:300,vx:0,vy:0},letters=[],hazards=[],index=0,done=0,oxygen=100,ready=false;function setup(){index=0;ready=false;letters=[...e.target.en,...'xyz'].map(ch=>({ch,x:Arcade.rand(60,840),y:Arcade.rand(underwater?170:80,540)}));hazards=Array.from({length:underwater?5:7},()=>({x:Arcade.rand(50,850),y:Arcade.rand(180,550),vx:Arcade.rand(-55,55),vy:Arcade.rand(-30,30),r:underwater?23:28}));e.mission(`${underwater?'深海寻字母':'星际收集'}：${e.target.zh} · ${e.target.en}`)}setup();
 e.move=p=>{if(e.pointer.down){player.vx=(p.x-player.x)*2;player.vy=(p.y-player.y)*2}};
 e.update=dt=>{let ax=(e.keys.has('ArrowRight')?1:0)-(e.keys.has('ArrowLeft')?1:0),ay=(e.keys.has('ArrowDown')?1:0)-(e.keys.has('ArrowUp')?1:0);player.vx+=ax*290*dt;player.vy+=ay*290*dt;if(e.keys.has(' ')){if(underwater)player.vy-=500*dt;else {player.vx*=.86;player.vy*=.86}}player.vx=Arcade.clamp(player.vx,-230,230);player.vy=Arcade.clamp(player.vy,-230,230);player.x+=player.vx*dt;player.y+=player.vy*dt;player.vx*=Math.pow(underwater?.35:.8,dt);player.vy*=Math.pow(underwater?.35:.8,dt);
   if(underwater){player.x=Arcade.clamp(player.x,25,875);player.y=Arcade.clamp(player.y,45,565);if(player.y<85){oxygen=Math.min(100,oxygen+60*dt);if(ready){done++;e.score+=200;if(done>=e.pool.length){e.end(true,'深海任务完成！');return}e.nextWord();setup()}}else oxygen-=4*dt;if(oxygen<=0){e.hit();oxygen=100;player.y=55;player.vy=0}}else {player.x=(player.x+900)%900;player.y=(player.y+600)%600}
   for(const h of hazards){h.x+=h.vx*dt;h.y+=h.vy*dt;if(h.x<25||h.x>875)h.vx*=-1;if(h.y<120||h.y>570)h.vy*=-1;if(Arcade.dist(h,player)<h.r+16)e.hit()}
   if(!ready){let l=letters.find(l=>l.ch===e.target.en[index]&&Arcade.dist(l,player)<32);if(l){letters=letters.filter(a=>a!==l);index++;e.score+=40;if(index===e.target.en.length){if(underwater){ready=true;e.mission('单词已收齐！返回水面交付并补氧。')}else {done++;if(done>=e.pool.length){e.end(true,'星际任务完成！');return}e.nextWord();setup()}}else e.mission(`${e.target.zh}：${e.target.en.slice(0,index)}${'＿'.repeat(e.target.en.length-index)}　下一个 ${e.target.en[index]}`)}}e.hud(`${done}/${e.pool.length} 词 · ${underwater?'氧气 '+Math.ceil(oxygen):'生命 '+e.lives}`);
 };
 e.draw=()=>{if(underwater){e.rect(0,90,900,510,'#133d58');e.rect(0,85,900,5,'#73d6d0')}else for(let i=0;i<45;i++)e.circle((i*137)%900,(i*83)%600,1.4,'#6589b9');letters.forEach(l=>{e.circle(l.x,l.y,20,l.ch===e.target.en[index]?'#f4c56d':'#7594b5');e.text(l.ch,l.x,l.y+7,23,'#10243b')});hazards.forEach(h=>{e.circle(h.x,h.y,h.r,underwater?'#b58fce':'#747f91');if(underwater)e.text('≋',h.x,h.y+10,35,'#283456')});e.circle(player.x,player.y,19,'#70e5ba');e.text(underwater?'●':'▲',player.x,player.y+7,24,'#11352d');if(underwater){e.rect(260,20,380,14,'#355674',7);e.rect(260,20,3.8*oxygen,14,'#7ee4c0',7);e.text('水面补氧',110,56,17)}};e.state={player,get letters(){return letters},hazards};
}
Arcade.register('G16',()=>letterVoyage('G16',false));Arcade.register('G18',()=>letterVoyage('G18',true));
Arcade.register('G17',()=>{
 const e=Arcade.start('G17','左右移动挡板接球，球碰挡板的位置决定反弹角度。清空砖墙进入下一关，共 3 关。掉落奖励有加宽和减速；漏球扣生命。',[{key:' ',label:'发球'}]);
 let paddle={x:450,w:120},ball={x:450,y:520,vx:150,vy:-280,stuck:true},bricks=[],drops=[];function setup(){bricks=Array.from({length:50},(_,i)=>({x:65+i%10*77,y:70+Math.floor(i/10)*38,w:70,h:30,hp:e.level>1&&i<10?2:1,word:e.pool[i%e.pool.length]}));ball.stuck=true;drops=[];e.mission(`第 ${e.level} 关：清空词汇砖墙 · ${e.pool.slice(0,3).map(w=>w.en+' '+w.zh).join(' / ')}`)}setup();function launch(){if(ball.stuck){ball.stuck=false;ball.vx=150;ball.vy=-280-e.level*20}}e.tap=launch;e.move=p=>paddle.x=Arcade.clamp(p.x,paddle.w/2,900-paddle.w/2);
 e.update=dt=>{paddle.x=Arcade.clamp(paddle.x+((e.keys.has('ArrowRight')?1:0)-(e.keys.has('ArrowLeft')?1:0))*450*dt,paddle.w/2,900-paddle.w/2);if(e.pressed.has(' '))launch();if(ball.stuck){ball.x=paddle.x;ball.y=520}else {let oldY=ball.y;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<10||ball.x>890){ball.vx*=-1;ball.x=Arcade.clamp(ball.x,10,890)}if(ball.y<10){ball.vy=Math.abs(ball.vy);ball.y=10}if(ball.vy>0&&oldY<=523&&ball.y>=523&&Math.abs(ball.x-paddle.x)<paddle.w/2+10){let a=(ball.x-paddle.x)/(paddle.w/2)*1.05,speed=Math.min(450,Math.hypot(ball.vx,ball.vy)+10);ball.vx=Math.sin(a)*speed;ball.vy=-Math.cos(a)*speed;ball.y=522}for(const b of bricks)if(b.hp>0&&ball.x>b.x-8&&ball.x<b.x+b.w+8&&ball.y>b.y-8&&ball.y<b.y+b.h+8){b.hp--;e.score+=20;if(oldY<b.y||oldY>b.y+b.h)ball.vy*=-1;else ball.vx*=-1;if(!b.hp&&Math.random()<.2)drops.push({x:b.x+b.w/2,y:b.y,type:Math.random()<.5?'wide':'slow'});break}if(ball.y>620){e.hit();ball.stuck=true;paddle.w=120}if(bricks.every(b=>!b.hp)){if(e.level>=e.stageLimit){e.end(true,'本盘砖墙全部清空！');return}e.level++;setup()}}for(const d of drops){d.y+=130*dt;if(d.y>520&&Math.abs(d.x-paddle.x)<paddle.w/2){if(d.type==='wide')paddle.w=190;else {ball.vx*=.8;ball.vy*=.8}d.remove=true}}drops=drops.filter(d=>d.y<610&&!d.remove);e.hud()};
 e.draw=()=>{bricks.forEach(b=>{if(!b.hp)return;e.rect(b.x,b.y,b.w,b.h,b.hp>1?'#ba94e5':['#7ad4b4','#e7be72','#80a8df','#e98fab','#b896e1'][Math.floor((b.y-70)/38)],5);e.label(b.word,b.x+b.w/2,b.y+21,b.w-6,13,'#17263a')});e.rect(paddle.x-paddle.w/2,535,paddle.w,15,'#6ae6bd',7);e.circle(ball.x,ball.y,9,'#fff1bf');drops.forEach(d=>e.word(d.type==='wide'?'↔':'↓',d.x,d.y));if(ball.stuck)e.text('按发球开始',450,460,22)};e.state={ball,paddle,get bricks(){return bricks}};
});
Arcade.register('G22',()=>{
 const e=Arcade.start('G22','拖动自己的下半场球拍击打圆盘，球拍速度会影响击球速度。守住底部球门，先得 7 分获胜。方向键移动球拍，空格发球。',[{key:' ',label:'发球'}]);
 let player={x:450,y:480,vx:0,vy:0},ai={x:450,y:100,vx:0,vy:0},puck={x:450,y:300,vx:0,vy:0},you=0,cpu=0,serve=true;const left=110,right=790,top=30,bottom=570;
 function hud(){e.hud(`你 ${you} : ${cpu} 对手 · 先得 7 分`);e.mission(`本场词汇：${e.target.en} = ${e.target.zh}　下方球拍由你控制`)}hud();
 function start(){if(serve){puck.x=450;puck.y=300;puck.vx=Arcade.rand(-100,100);puck.vy=180;serve=false}}e.tap=p=>{start();player.x=Arcade.clamp(p.x,left+30,right-30);player.y=Arcade.clamp(p.y,335,bottom-30)};e.move=(p,old)=>{if(e.pointer.down){player.vx=Arcade.clamp((p.x-player.x)*8,-700,700);player.vy=Arcade.clamp((p.y-player.y)*8,-700,700);player.x=Arcade.clamp(p.x,left+30,right-30);player.y=Arcade.clamp(p.y,335,bottom-30)}};
 function collide(b){let dx=puck.x-b.x,dy=puck.y-b.y,d=Math.hypot(dx,dy);if(d<45){let nx=dx/(d||1),ny=dy/(d||1);puck.x=b.x+nx*46;puck.y=b.y+ny*46;let v=(puck.vx-b.vx)*nx+(puck.vy-b.vy)*ny;if(v<0){puck.vx-=2*v*nx;puck.vy-=2*v*ny}let speed=Math.hypot(puck.vx,puck.vy);if(speed>650){puck.vx*=650/speed;puck.vy*=650/speed}}}
 e.update=dt=>{if(e.pressed.has(' '))start();let vx=((e.keys.has('ArrowRight')?1:0)-(e.keys.has('ArrowLeft')?1:0))*400,vy=((e.keys.has('ArrowDown')?1:0)-(e.keys.has('ArrowUp')?1:0))*400;if(vx||vy){player.vx=vx;player.vy=vy;player.x=Arcade.clamp(player.x+vx*dt,left+30,right-30);player.y=Arcade.clamp(player.y+vy*dt,335,bottom-30)}ai.vx=Arcade.clamp((puck.x-ai.x)*3,-260,260);ai.vy=Arcade.clamp(((puck.y<280?puck.y-45:110)-ai.y)*3,-180,180);ai.x=Arcade.clamp(ai.x+ai.vx*dt,left+30,right-30);ai.y=Arcade.clamp(ai.y+ai.vy*dt,top+30,265);if(!serve){puck.x+=puck.vx*dt;puck.y+=puck.vy*dt;puck.vx*=Math.pow(.98,dt);puck.vy*=Math.pow(.98,dt);if(puck.x<left+15||puck.x>right-15){puck.vx*=-1;puck.x=Arcade.clamp(puck.x,left+15,right-15)}let goal=puck.x>350&&puck.x<550;if(puck.y<top+15){if(goal){you++;e.score+=100;serve=true;e.nextWord()}else {puck.vy=Math.abs(puck.vy);puck.y=top+15}}if(puck.y>bottom-15){if(goal){cpu++;serve=true}else {puck.vy=-Math.abs(puck.vy);puck.y=bottom-15}}collide(player);collide(ai);if(you>=7||cpu>=7)e.end(you>=7,you>=7?'7 分获胜！':'对手先得 7 分');hud()}player.vx*=.85;player.vy*=.85};
 e.draw=()=>{e.rect(left,top,right-left,bottom-top,'#173e53',16);e.ctx.strokeStyle='#94c8d6';e.ctx.lineWidth=3;e.ctx.strokeRect(left,top,right-left,bottom-top);e.ctx.beginPath();e.ctx.moveTo(left,300);e.ctx.lineTo(right,300);e.ctx.stroke();e.circle(450,300,65,'#23576a');e.rect(350,top-5,200,10,'#ef8f9c');e.rect(350,bottom-5,200,10,'#77e7be');e.circle(ai.x,ai.y,30,'#ef8f9c');e.circle(player.x,player.y,30,'#77e7be');e.circle(puck.x,puck.y,15,'#fff1c1');if(serve)e.text('点击场地 / 发球继续',450,340,21)};e.state={player,ai,puck,get serve(){return serve}};
});
Arcade.register('G23',()=>{
 const e=Arcade.start('G23','左右移动，发射子弹消灭逐步下降的敌阵。掩体会被敌我子弹破坏；敌人越少移动越快。守住底线，清空 3 波敌阵获胜。',[{key:' ',label:'射击'}]);
 let x=450,shots=[],enemyShots=[],enemies=[],shields=[],dir=1,step=0,fire=0,enemyFire=0,ufo={x:-80,y:35};function setup(){enemies=Array.from({length:40},(_,i)=>({x:110+i%10*65,y:90+Math.floor(i/10)*45,word:e.pool[i%e.pool.length]}));shields=[];for(let k=0;k<4;k++)for(let r=0;r<3;r++)for(let c=0;c<7;c++)if(!(r===2&&c>1&&c<5))shields.push({x:150+k*180+c*12,y:440+r*12});dir=1;shots=[];enemyShots=[];e.nextWord();e.mission(`优先击中 ${e.target.zh} · ${e.target.en} 可得额外奖励；消灭所有敌人通关`)}setup();e.move=p=>x=Arcade.clamp(p.x,30,870);e.tap=()=>{if(fire<=0){shots.push({x,y:530});fire=.28}};
 e.update=dt=>{x=Arcade.clamp(x+((e.keys.has('ArrowRight')?1:0)-(e.keys.has('ArrowLeft')?1:0))*320*dt,30,870);fire-=dt;enemyFire-=dt;if(e.keys.has(' ')&&fire<=0)e.tap();step+=dt;if(step>Math.max(.07,.62-enemies.length*.001-(40-enemies.length)*.012-e.level*.05)){step=0;let edge=enemies.some(a=>a.x+dir*15<40||a.x+dir*15>860);if(edge){dir*=-1;enemies.forEach(a=>a.y+=22)}else enemies.forEach(a=>a.x+=dir*15)}if(enemyFire<=0&&enemies.length){let a=Arcade.pick(enemies);enemyShots.push({x:a.x,y:a.y});enemyFire=Math.max(.28,1.15-e.level*.18)}ufo.x+=65*dt;if(ufo.x>980)ufo.x=-180;
   for(const s of shots){s.y-=470*dt;let a=enemies.find(a=>Math.abs(a.x-s.x)<25&&Math.abs(a.y-s.y)<18);if(a){a.dead=true;s.dead=true;e.score+=a.word.en===e.target.en?60:20}if(Math.abs(s.x-ufo.x)<35&&Math.abs(s.y-ufo.y)<15){e.score+=150;ufo.x=-300;s.dead=true}}
   for(const s of enemyShots){s.y+=(170+e.level*35)*dt;if(Math.abs(s.x-x)<24&&s.y>515&&s.y<553){s.dead=true;e.hit()}}for(const s of [...shots,...enemyShots]){let shield=shields.find(a=>Math.abs(a.x-s.x)<8&&Math.abs(a.y-s.y)<9);if(shield){shield.dead=true;s.dead=true}}shots=shots.filter(s=>s.y>-20&&!s.dead);enemyShots=enemyShots.filter(s=>s.y<610&&!s.dead);shields=shields.filter(a=>!a.dead);enemies=enemies.filter(a=>!a.dead);if(enemies.some(a=>a.y>490))e.end(false,'敌阵突破防线');else if(!enemies.length){if(e.level>=e.stageLimit)e.end(true,'本盘敌阵全部击退！');else {e.level++;setup()}}e.hud()};
 e.draw=()=>{enemies.forEach(a=>{e.rect(a.x-22,a.y-13,44,26,['#e9bf6d','#a6d39b','#9db9e6'][e.level-1],5);e.label(a.word,a.x,a.y+5,40,11,'#17243b')});shields.forEach(a=>e.rect(a.x,a.y,11,11,'#7bd0ae'));shots.forEach(s=>e.rect(s.x-2,s.y,4,14,'#e9f8bf'));enemyShots.forEach(s=>e.rect(s.x-3,s.y,6,12,'#f389a1'));e.rect(x-25,535,50,16,'#77e6bd',5);e.rect(x-4,522,8,15,'#77e6bd');e.rect(ufo.x-30,25,60,20,'#d6819f',10)};e.state={get enemies(){return enemies},get shields(){return shields},get shots(){return shots}};
});
Arcade.register('G27',()=>{
 const e=Arcade.start('G27','四方向驾驶飞机并射击。每关 3 次翻滚可短暂无敌；击破编队、捡取火力补给，击败关底大型飞机。共 3 关，碰撞或中弹扣生命。',[{key:' ',label:'射击'},{key:'x',label:'翻滚'}]);
 let player={x:450,y:500},enemies=[],shots=[],enemyShots=[],drops=[],spawn=0,fire=0,rolls=3,rolling=0,stageTime=0,bossSpawned=false,power=1;
 function mission(){e.mission(`第 ${e.level} 关空战 · 词汇奖励：${e.target.zh} · ${e.target.en}　击败关底飞机`)}mission();e.move=p=>{if(e.pointer.down){player.x=Arcade.clamp(p.x,25,875);player.y=Arcade.clamp(p.y,70,565)}};e.tap=()=>{if(fire<=0){for(let i=0;i<power;i++)shots.push({x:player.x+(i-(power-1)/2)*16,y:player.y-24});fire=.18}};
 e.update=dt=>{stageTime+=dt;spawn-=dt;fire-=dt;rolling=Math.max(0,rolling-dt);player.x=Arcade.clamp(player.x+((e.keys.has('ArrowRight')?1:0)-(e.keys.has('ArrowLeft')?1:0))*270*dt,25,875);player.y=Arcade.clamp(player.y+((e.keys.has('ArrowDown')?1:0)-(e.keys.has('ArrowUp')?1:0))*270*dt,50,570);if(e.keys.has(' ')||e.pointer.down)e.tap();if(e.pressed.has('x')&&rolls>0&&rolling<=0){rolls--;rolling=1.5;e.invincible=1.5}if(!bossSpawned&&stageTime<22&&spawn<=0){let origin=Arcade.rand(70,750);for(let i=0;i<3;i++)enemies.push({x:origin+i*45,y:-50-i*40,base:origin+i*45,phase:Math.random()*6,hp:1,boss:false,fire:Arcade.rand(.7,2),word:Arcade.pick(e.pool)});spawn=1.4}if(stageTime>=24&&!bossSpawned){enemies.push({x:450,y:-90,base:450,hp:25+e.level*10,boss:true,fire:1,phase:0,word:e.target});bossSpawned=true}
   for(const a of enemies){a.y+=dt*(a.boss&&a.y>110?0:a.boss?65:100+e.level*20);a.x=a.base+Math.sin(e.elapsed*1.4+a.phase)*(a.boss?220:60);a.fire-=dt;if(a.fire<=0&&a.y>30){let dx=player.x-a.x,dy=player.y-a.y,d=Math.hypot(dx,dy)||1;enemyShots.push({x:a.x,y:a.y,vx:dx/d*170,vy:dy/d*170});if(a.boss)for(let vx of [-100,100])enemyShots.push({x:a.x,y:a.y,vx,vy:180});a.fire=a.boss?.8:1.8}if(Arcade.dist(a,player)<(a.boss?65:30)&&!rolling)e.hit()}
   for(const s of shots){s.y-=500*dt;let a=enemies.find(a=>Math.abs(a.x-s.x)<(a.boss?70:24)&&Math.abs(a.y-s.y)<(a.boss?40:24));if(a){s.dead=true;a.hp--;if(a.hp<=0){a.dead=true;e.score+=a.boss?1000:a.word.en===e.target.en?100:40;if(!a.boss&&Math.random()<.2)drops.push({x:a.x,y:a.y})}}}for(const s of enemyShots){s.x+=s.vx*dt;s.y+=s.vy*dt;if(Arcade.dist(s,player)<18){s.dead=true;if(!rolling)e.hit()}}for(const d of drops){d.y+=75*dt;if(Arcade.dist(d,player)<30){power=Math.min(3,power+1);d.dead=true;e.score+=50}}
   const bossDead=enemies.some(a=>a.boss&&a.dead);enemies=enemies.filter(a=>!a.dead&&a.y<660);shots=shots.filter(s=>!s.dead&&s.y>-30);enemyShots=enemyShots.filter(s=>!s.dead&&s.y<640&&s.x>-30&&s.x<930);drops=drops.filter(d=>!d.dead&&d.y<640);if(bossDead){if(e.level>=e.stageLimit){e.end(true,'本盘空战完成！');return}e.level++;stageTime=0;bossSpawned=false;enemies=[];enemyShots=[];rolls=3;e.nextWord();mission()}e.hud(`生命 ${e.lives} · 翻滚 ${rolls} · 火力 ${power} · 第 ${e.level} 关`)};
 function plane(x,y,size,color,up){e.rect(x-size*.12,y-size*.55,size*.24,size,color,5);e.rect(x-size*.65,y-size*.08,size*1.3,size*.2,color,4);e.rect(x-size*.35,y+(up?.3:-.4)*size,size*.7,size*.12,color,3)}
 e.draw=()=>{e.rect(0,0,900,600,'#153e59');for(let i=0;i<15;i++)e.rect((i*193)%900,((i*91+e.elapsed*70)%650)-50,80,3,'#2c5970');enemies.forEach(a=>{plane(a.x,a.y,a.boss?110:36,a.boss?'#eab477':'#da939c',false);e.label(a.word,a.x,a.y+35,a.boss?100:42,12,'#edf3ff');if(a.boss)e.text(`HP ${a.hp}`,a.x,a.y-65,18)});shots.forEach(s=>e.rect(s.x-2,s.y,4,17,'#f8efb6'));enemyShots.forEach(s=>e.circle(s.x,s.y,5,'#ff8d88'));drops.forEach(d=>e.word('P',d.x,d.y));if(!e.invincible||Math.floor(e.elapsed*10)%2)plane(player.x,player.y,40,rolling?'#b6a4f2':'#74e1bd',true)};e.state={player,get enemies(){return enemies},get rolls(){return rolls},get shots(){return shots}};
});
