Arcade.register('G05',()=>{
 const e=Arcade.start('G05','交换相邻的两个方块，横向或纵向凑齐 3 个即可消除。无消除的交换会退回。25 步内收集目标词，四连或五连制造特殊方块。',[{key:' ',label:'重排（扣分）'}]);
 const types=e.pool.slice(0,5),N=7,S=64,ox=226,oy=85;let b=Array.from({length:N},()=>Array(N).fill(0)),special=new Map(),selected=null,moves=25,collected=0,goal=15,busy=0;
 function fresh(){for(let r=0;r<N;r++)for(let c=0;c<N;c++){do{b[r][c]=Math.floor(Math.random()*types.length)}while((c>1&&b[r][c]===b[r][c-1]&&b[r][c]===b[r][c-2])||(r>1&&b[r][c]===b[r-1][c]&&b[r][c]===b[r-2][c]))}}fresh();
 const swap=(a,d)=>{[b[a.r][a.c],b[d.r][d.c]]=[b[d.r][d.c],b[a.r][a.c]];let i=a.r*N+a.c,j=d.r*N+d.c,sp=special.get(i),sq=special.get(j);special.delete(i);special.delete(j);if(sp)special.set(j,sp);if(sq)special.set(i,sq)};
 function possible(){for(let r=0;r<N;r++)for(let c=0;c<N;c++)for(let [dr,dc]of [[0,1],[1,0]])if(r+dr<N&&c+dc<N){let a={r,c},d={r:r+dr,c:c+dc};swap(a,d);let yes=Arcade.matches(b).length;swap(a,d);if(yes)return true}return false}
 function hud(){e.hud(`剩余 ${moves} 步 · 目标 ${collected}/${goal}`);e.mission(`收集 ${types[0].zh} · ${types[0].en}　目标 ${goal} 个`)}
 function resolve(depth=1){let matches=Arcade.matches(b);if(!matches.length){busy=0;if(collected>=goal)e.end(true);else if(moves<=0)e.end(false,'步数用完，再挑战一次！');else if(!possible()){fresh();special.clear();e.mission('没有可交换组合，已自动重新排列。')}hud();return}let clear=new Set(matches),newSpecial=null;
   if(depth===1){for(const i of matches){let r=Math.floor(i/N),c=i%N,v=b[r][c],horizontal=[],vertical=[];for(let x=c;x<N&&b[r][x]===v;x++)horizontal.push(r*N+x);for(let y=r;y<N&&b[y][c]===v;y++)vertical.push(y*N+c);let run=horizontal.length>=4?horizontal:vertical.length>=4?vertical:null;if(run){newSpecial={i:run[Math.floor(run.length/2)],type:run.length>=5?'burst':'row'};break}}}
   for(const i of [...clear])if(special.has(i)){let r=Math.floor(i/N),c=i%N;if(special.get(i)==='row')for(let x=0;x<N;x++)clear.add(r*N+x);else for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(b[y][x]===b[r][c])clear.add(y*N+x);special.delete(i)}
   clear.forEach(i=>{let r=Math.floor(i/N),c=i%N;if(b[r][c]===0)collected++;b[r][c]=-1});e.score+=clear.size*10*depth;hud();busy=.22;
   later(()=>{for(let c=0;c<N;c++){let column=[];for(let r=N-1;r>=0;r--)if(b[r][c]>=0)column.push(b[r][c]);for(let r=N-1;r>=0;r--)b[r][c]=column[N-1-r]??Math.floor(Math.random()*types.length)}special.clear();if(newSpecial)special.set(newSpecial.i,newSpecial.type);resolve(depth+1)},240);
 }
 e.tap=p=>{if(busy||moves<=0)return;let c=Math.floor((p.x-ox)/S),r=Math.floor((p.y-oy)/S);if(r<0||c<0||r>=N||c>=N)return;let cell={r,c};if(!selected){selected=cell;return}if(Math.abs(selected.r-r)+Math.abs(selected.c-c)!==1){selected=cell;return}swap(selected,cell);if(!Arcade.matches(b).length)swap(selected,cell);else {moves--;busy=1;resolve()}selected=null;hud()};
 e.update=()=>{if(e.pressed.has(' ')&&!busy){fresh();special.clear();e.score=Math.max(0,e.score-50);hud()}};
 e.draw=()=>{for(let r=0;r<N;r++)for(let c=0;c<N;c++){let v=b[r][c],x=ox+c*S,y=oy+r*S;e.rect(x+2,y+2,S-4,S-4,['#6bd2aa','#f4c875','#91baf8','#ed8aac','#c6a4ed'][v]||'#20314c',9);if(v>=0){e.label(types[v],x+S/2,y+S/2+5,S-10,15,'#14223b');if(special.has(r*N+c))e.text('★',x+S-12,y+17,16,'#fff')}if(selected?.r===r&&selected?.c===c){e.ctx.strokeStyle='#fff';e.ctx.lineWidth=4;e.ctx.strokeRect(x+3,y+3,S-6,S-6)}}e.text('交换相邻方块 · 三连消除 · 连锁加分',450,570,19)};e.state={get board(){return b},get moves(){return moves}};hud();
});
Arcade.register('G07',()=>{
 const e=Arcade.start('G07','调整方向，发射泡泡。3 个以上同色泡泡相连即消除，悬空泡泡会掉落。墙壁可反弹，每 5 次射击顶部下降。清空即可获胜。',[{key:' ',label:'发射'},{key:'x',label:'换球'}]);
 const R=23,dx=48,dy=41,cols=13,ox=138,oy=45,colors=['#f0b75b','#76c9a4','#8db7ef','#ec89b5'];let cells=new Map(),ball=null,angle=-Math.PI/2,current=0,next=1,shots=0,drop=0;
 const k=(r,c)=>r+','+c,xy=(r,c)=>({x:ox+c*dx+(r%2)*24,y:oy+r*dy+drop});function neighbors(r,c){let off=r%2?1:-1;return [[r,c-1],[r,c+1],[r-1,c],[r-1,c+off],[r+1,c],[r+1,c+off]].filter(([a,b])=>a>=0&&b>=0&&b<cols)}
 for(let r=0;r<5;r++)for(let c=0;c<cols;c++)cells.set(k(r,c),{r,c,color:Math.floor(Math.random()*4)});
 function hud(){e.hud(`剩余 ${cells.size} 泡泡 · 第 ${shots+1} 发`);e.mission(`泡泡颜色对应词汇：${e.pool.slice(0,4).map(w=>w.en+' '+w.zh).join(' / ')}`)}
 function shoot(){if(ball)return;ball={x:450,y:552,vx:Math.cos(angle)*540,vy:Math.sin(angle)*540,color:current};current=next;next=Math.floor(Math.random()*4)}
 function attach(){let options=[];for(let c=0;c<cols;c++)if(!cells.has(k(0,c)))options.push([0,c]);for(const cell of cells.values())for(const n of neighbors(cell.r,cell.c))if(!cells.has(k(...n)))options.push(n);options.sort((a,b)=>Arcade.dist(xy(...a),ball)-Arcade.dist(xy(...b),ball));let pos=options[0];if(!pos){e.end(false);return}let cell={r:pos[0],c:pos[1],color:ball.color};cells.set(k(...pos),cell);ball=null;shots++;
   let cluster=new Set(),queue=[cell];while(queue.length){let p=queue.pop(),key=k(p.r,p.c);if(cluster.has(key))continue;cluster.add(key);neighbors(p.r,p.c).forEach(n=>{let q=cells.get(k(...n));if(q&&q.color===cell.color&&!cluster.has(k(...n)))queue.push(q)})}if(cluster.size>=3){cluster.forEach(key=>cells.delete(key));e.score+=cluster.size*20;let anchored=new Set(),q=[...cells.values()].filter(p=>p.r===0);while(q.length){let p=q.pop(),key=k(p.r,p.c);if(anchored.has(key))continue;anchored.add(key);neighbors(p.r,p.c).forEach(n=>{let a=cells.get(k(...n));if(a&&!anchored.has(k(...n)))q.push(a)})}for(const key of cells.keys())if(!anchored.has(key)){cells.delete(key);e.score+=30}}
   if(shots%5===0)drop+=25;if(!cells.size)e.end(true,'泡泡全部清空！');else if([...cells.values()].some(p=>xy(p.r,p.c).y>482))e.end(false,'泡泡到达底线！');hud();
 }
 e.tap=p=>{angle=Arcade.clamp(Math.atan2(p.y-552,p.x-450),-Math.PI+.18,-.18);shoot()};e.move=p=>{if(p.y<520)angle=Arcade.clamp(Math.atan2(p.y-552,p.x-450),-Math.PI+.18,-.18)};
 e.update=dt=>{if(e.keys.has('ArrowLeft'))angle-=dt*1.7;if(e.keys.has('ArrowRight'))angle+=dt*1.7;angle=Arcade.clamp(angle,-Math.PI+.18,-.18);if(e.pressed.has(' '))shoot();if(e.pressed.has('x'))[current,next]=[next,current];if(ball){ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<ox-R||ball.x>ox+(cols-1)*dx+24+R){ball.vx*=-1;ball.x=Arcade.clamp(ball.x,ox-R,ox+(cols-1)*dx+24+R)}if(ball.y<=oy+drop||[...cells.values()].some(p=>Arcade.dist(xy(p.r,p.c),ball)<R*2-1))attach()}};
 e.draw=()=>{for(let cell of cells.values()){let p=xy(cell.r,cell.c);e.circle(p.x,p.y,R,colors[cell.color]);e.label(e.pool[cell.color],p.x,p.y+5,R*2-6,12,'#12243b')}e.ctx.strokeStyle='#ecf0ff88';e.ctx.setLineDash([6,7]);e.ctx.beginPath();e.ctx.moveTo(450,552);e.ctx.lineTo(450+Math.cos(angle)*110,552+Math.sin(angle)*110);e.ctx.stroke();e.ctx.setLineDash([]);e.circle(450,552,R,colors[current]);e.label(e.pool[current],450,557,R*2-6,12,'#12243b');e.circle(535,557,17,colors[next]);e.label(e.pool[next],535,561,30,11,'#12243b');e.text('当前：'+e.pool[current].en,270,560,16);e.text('下一颗：'+e.pool[next].en,680,560,16);if(ball){e.circle(ball.x,ball.y,R,colors[ball.color]);e.label(e.pool[ball.color],ball.x,ball.y+5,R*2-6,12,'#12243b')}e.rect(110,510,670,2,'#ec7499')};e.state={cells,get ball(){return ball}};hud();
});
Arcade.register('G20',()=>{
 const e=Arcade.start('G20','连接相邻字母组成词库中的词，可以横、竖、斜向转弯，同一条路径不能重复格子。找到所有主题词和贯穿两侧的主题词即可完成。',[{key:'x',label:'提示（扣分）'},{key:' ',label:'提交路径'}]);
 const list=ArcadeRules.shuffle(e.pool).slice(0,6).sort((a,b)=>b.en.length-a.en.length),cols=Math.min(6,list[0].en.length),total=list.reduce((n,w)=>n+w.en.length,0),rows=Math.ceil(total/cols),S=Math.min(66,450/rows),ox=450-cols*S/2,oy=70;let board=[],paths=[],cursor=0,found=new Set(),path=[];
 for(const w of list){let cells=[];for(const ch of w.en){let r=Math.floor(cursor/cols),c=r%2?cols-1-cursor%cols:cursor%cols;board[r*cols+c]=ch;cells.push(r*cols+c);cursor++}paths.push(cells)}for(let i=0;i<rows*cols;i++)board[i]??=String.fromCharCode(97+Math.random()*26|0);
 function hud(){e.hud(`主题词 ${found.size}/${list.length}`);e.mission(`本盘词库主题 · ${list.map(w=>w.zh).join('、')}　金色贯穿词：${list[0].zh}`)}
 function cell(p){let c=Math.floor((p.x-ox)/S),r=Math.floor((p.y-oy)/S);return r>=0&&c>=0&&r<rows&&c<cols?r*cols+c:-1}
 function add(i){if(i<0||[...found].some(j=>paths[j].includes(i)))return;if(path.at(-2)===i){path.pop();return}if(path.includes(i))return;let last=path.at(-1);if(last!==undefined&&Math.max(Math.abs(Math.floor(last/cols)-Math.floor(i/cols)),Math.abs(last%cols-i%cols))!==1)return;path.push(i)}
 function submit(){let text=path.map(i=>board[i]).join(''),index=list.findIndex((w,i)=>!found.has(i)&&(w.en===text||w.en===[...text].reverse().join('')));if(index>=0){found.add(index);paths[index]=[...path];e.score+=index===0?200:100;hud();if(found.size===list.length)e.end(true,'主题词全部找到！')}path=[]}
 e.tap=p=>{let i=cell(p);if(i===path.at(-1)&&path.length>1)submit();else add(i)};e.move=p=>{if(e.pointer.down)add(cell(p))};e.release=()=>{if(path.length>1){let text=path.map(i=>board[i]).join('');if(list.some(w=>w.en===text||w.en===[...text].reverse().join('')))submit()}};
 e.update=()=>{if(e.pressed.has(' '))submit();if(e.pressed.has('x')){let idx=list.findIndex((w,i)=>!found.has(i));if(idx>=0){path=paths[idx].slice(0,2);e.score=Math.max(0,e.score-25)}}};
 e.draw=()=>{for(let i=0;i<board.length;i++){let x=ox+(i%cols)*S+S/2,y=oy+Math.floor(i/cols)*S+S/2,idx=[...found].find(j=>paths[j].includes(i));e.circle(x,y,S*.39,idx!==undefined?(idx===0?'#f3c565':'#83bce7'):path.includes(i)?'#8edbbe':'#273e5b');e.text(board[i],x,y+7,24,idx!==undefined||path.includes(i)?'#10233b':'#f1f5ff')}e.text(path.map(i=>board[i]).join(''),450,550,22,'#f7c775');e.text('点最后一格或按提交确认 · 可连续拖动',450,580,16)};e.state={board,paths,list,get path(){return path}};hud();
});
